### ISSUE TITLE
error parsing a packet with more than one record

### ISSUE THREAD

**Issue by nininini123** [CroatiaControlLtd/asterix#105]
I read the codes in _inputparser.cpp_ and i find that it deals with a packet as 

> n * (CAT + LEN + FSPEC + ITEMS)

as in codes:

`

          AsterixData* InputParser::parsePacket(const unsigned char* m_pBuffer, unsigned int m_nBufferSize, unsigned long nTimestamp)
          {
            AsterixData* pAsterixData = new AsterixData();
            unsigned int m_nPos = 0;
            unsigned int m_nDataLength = 0;
            const unsigned char* m_pData = m_pBuffer; // internally used pointer to parsed data
            while(m_nPos < m_nBufferSize)
            {
              bool bOK = true;
              m_nDataLength = m_nBufferSize-m_nPos;
              if (m_nDataLength <= 3)
              {
                  Tracer::Error("Not enough data for Asterix header (%d)", m_nDataLength);
                  break;
              }
              while(bOK && m_nDataLength > 3)
              {
                unsigned char nCategory = *m_pData;
                m_pData ++; m_nPos ++;
                unsigned short dataLen = *m_pData; // length
          #ifdef _DEBUG
                unsigned char nDataLen1 = *m_pData;
          #endif
                m_pData ++; m_nPos ++;
          #ifdef _DEBUG
                unsigned char nDataLen2 = *m_pData;
          #endif
                dataLen <<= 8;
                dataLen |= *m_pData;
                m_pData ++; m_nPos ++;
                // parse Asterix data
                if (dataLen <= 3 || dataLen > m_nDataLength)
                {
                  Tracer::Error("Wrong Asterix data length (%d)", dataLen);
                  if (dataLen <= 3)
                  {
                    // otherwise finish
                    return pAsterixData;
                  }
                  // there is not enough data, but parse what is there
                  dataLen = (unsigned short)m_nDataLength;
                }
                m_nDataLength -= 3;
                dataLen -= 3;
          #ifdef _DEBUG
                std::stringstream buffer;
                buffer << std::hex << std::setfill('0') << std::setw(2) <<
            std::uppercase << static_cast<unsigned>(nCategory) << " ";
                buffer << std::hex << std::setfill('0') << std::setw(2) <<
                  std::uppercase << static_cast<unsigned>(nDataLen1) << " ";
                buffer << std::hex << std::setfill('0') << std::setw(2) <<
                  std::uppercase << static_cast<unsigned>(nDataLen2) << " ";
                for (int i = 0; i < dataLen; i++) {
                  buffer << std::hex << std::setfill('0') << std::setw(2) <<
                    std::uppercase << static_cast<unsigned>(m_pData[i]) << " ";
                }
                std::string hexString = buffer.str();
                hexString.erase(hexString.size() - 1);
                LOGDEBUG(1, "[%s]\n", hexString.c_str());
          #endif
                DataBlock* db = new DataBlock(m_pDefinition->getCategory(nCategory), dataLen, m_pData, nTimestamp);
                m_pData += dataLen;
                m_nPos += dataLen;
                pAsterixData->m_lDataBlocks.push_back(db);
                if (db->m_bFormatOK == false)
                {
                  break;
                }
                m_nDataLength -= dataLen;
              }
            }
            return pAsterixData;
          }

`

but according to the documents of Eurocontrol, it ought to be 

>  CAT + LEN + n * ( FSPEC + ITEMS)

so i suggest you put the codes( _line57~69_ ) below outside the while-loop
`

                unsigned char nCategory = *m_pData;
                m_pData ++; m_nPos ++;
                unsigned short dataLen = *m_pData; // length
          #ifdef _DEBUG
                unsigned char nDataLen1 = *m_pData;
          #endif
                m_pData ++; m_nPos ++;
          #ifdef _DEBUG
                unsigned char nDataLen2 = *m_pData;
          #endif
                dataLen <<= 8;
                dataLen |= *m_pData;
                m_pData ++; m_nPos ++;

`

**Comment by dsalantic** [comment]
Actually, there are two formats of Asterix record (correct me if I'm wrong):
Until Asterix specification v2.1:  CAT + LEN + n * ( FSPEC + ITEMS)
From Asterix specification v2.2:  n * (CAT + LEN + FSPEC + ITEMS)

I decided to support new format and that's how it is implemented now.
If you have an idea how to change function to recognize and support both formats let me know.
Or. maybe I should put an application flag to manually choose it ?

**Comment by ifsnop** [comment]
I think I'm feeding asterix with v2.1 output and it works correctly. Are
you sure that asterix only supports v2.2?

**Comment by dsalantic** [comment]
If you are not sending more then one item in record then both formats are equal.

**Comment by ifsnop** [comment]
Of course :D

But I use it daily, just an example I gathered: two data records inside one
datablock.

Cat +Len + fspec +data +fspec+data

It works ok, as expected.

30 00 7B FF F7 02 14 01 7C 65 E1 A8 72 2E 0B B3 0D 20 05 9F E0 10 03 BC 39
2A E2 04 64 B3 D8 B5 60 03 C6 50 00 30 B8 00 00 40 80 71 63 35 60 0C D7 50
8B C9 F9 2F A0 0F FE 60 07 9C 07 8F 16 26 46 20 F5 FF F7 02 14 01 7C 65 E3
A8 64 7B 0C 45 0D 1B 04 FF E0 08 02 BD 39 2A EB 04 64 B1 D7 9D E0 02 BE 80
00 30 90 00 00 40 8B 6A 35 30 FF EF FF 60 01 97 07 D6 15 41 4E 20 F5

> If you are not sending more then one item in record then both formats are
> equal
>

**Comment by nininini123** [comment]
aw turns out that it's my own mistake .thank you

**Comment by dsalantic** [comment]
Yes, actually it works for both formats.
