### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by fbarilla** [CroatiaControlLtd/asterix#107]
This is the error I'm getting after having installed the Python module and ran: 

python ./asterix/examples/read_pcap_file.py
Traceback (most recent call last):
  File "./asterix/examples/read_pcap_file.py", line 9, in <module>
    pcap = dpkt.pcap.Reader(f)
  File "/home/fbarilla/anaconda3/lib/python3.7/site-packages/dpkt/pcap.py", line 244, in __init__
    buf = self.__f.read(FileHdr.__hdr_len__)
  File "/home/fbarilla/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte

**Comment by fbarilla** [comment]
the easy fix is to change :

with open(sample_filename) as f:
by
with open(sample_filename, 'rb') as f:

sorry for the interruption :-)  

BTW, another question: do you have a module to convert CAT240 messages to image ? It would save me a lot of time if you have one.

**Comment by dsalantic** [comment]
Thanks for your comment. Now I fixed it in example.
Unfortunately, I don't have a modul to visualize CAT240.
Good luck with the implementation.
