### ISSUE TITLE
How to get pointer to datablocks in output

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#115]
I would like to be able to modify some dataitems (for example, sass-c v6.7 can't parse cat21v2.1/di271 and each time it founds a di with fx=1 then there is chance that the whole datablock would be thrown away).

So, I was planning to use CCLtd/asterix to give me pointers into datarecord to know where each dataitem starts, and then patch the offending bits, rebuilding the asterix datarecord.

Could you give me some hints for the best way to do it?

I have found DataItem::getText() as a good place, using m_pData address and storing it in strNewResult, but I think I need some pointer math to get the position relative to the beginning of the datarecord byte array.

Also the constructor for DataRecord, as it iterates throught all the dataitems may be a good place, Maybe (data - m_pItemDataStart) could give me the relative position from the beginning of the datarecord? But now I don't know where to store it  so it can be printed in the output.

So, can you give me a hint?

Thanks in advance.

**Comment by dsalantic** [comment]
Sorry, but I don't see an easy way how to do it. Asterix parser was not designed in the way to generate any asterix format, but only to parse it.
The cleanest way would be to implement a new functionality in Python to generate asterix binary from the parsed structure and maybe sometime I'll try to implement it, but it's a long way to that point.

**Comment by ifsnop** [comment]
Sorry, didn't explain myself. I don't want Asterix to generate any binary,
only to export (as additional JSON information) a pointer to the bytes that
are decoded for each data block.

Like in the text output, that shows the bytes decoded in hexa along with
the decoded text.

I have not been able to pinpoint the place in the source code to get that
information (a pointer to the bytes decoded relative to the beginning of
the data record) and be able to store the info in the output.

**Comment by dsalantic** [comment]
Will be fixed with #135 Implement extensive JSON output format
