### ISSUE TITLE
Error in decodification of I021/271 version 2.1

### ISSUE THREAD

**Issue by JorgeFMorais** [CroatiaControlLtd/asterix#116]
The field 271 is a variable type field. However in its definition in the standard version 2.1 the second (optional) octet does not follow the proper decoding criteria, this causes the decoder to interpret that there is a third or fourth octet that belongs to this field when no such thing is possible. This causes all the subsequent fields in the message to be incorrectly decoded. 

This error in definition was later ammended in version 2.4 which broke backwards compatibility with version 2.1. Therefore a special case must be implemented in order to correctly decode a CAT021 message of version 2.1.

**Comment by dsalantic** [comment]
I see the point, but unfortunately I don't see a way how to support both versions 2.1 and 2.4 with the same definition (if that's what you are suggesting).
The biggest problem with ASTERIX protocol, as I see it, is that there is no version indicator in the coded data, so it's impossible to automatically determine which format version to use when you receive data.
So, only solution is to manually choose correct XML format definition (e.g. asterix_cat021_2_1.xml or asterix_cat021_2_4.xml).
An improvement would be to implement an option in Python decoder to choose which version of category to use while parsing, and I have it in my todo list, but will have to find some time to implement it.
Thank you for your contribution and let me know if you have a suggestion for another fix.

**Comment by JorgeFMorais** [comment]
In addition to the pytho modification I would add an input argument to the C++ module for the user to select the category and version he wants to decode.
