### ISSUE TITLE
glibc version 2.1 behaves diffrently than glibc 2.0.6

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#122]
I would like to add a warning, just close when readed. Sometime between 1997 and 1999 this was changed:

`
The glibc implementation of the functions snprintf() and vsnprintf() conforms to the C99 standard, that is, behaves as described above, since glibc version 2.1. Until glibc 2.0.6 they would return -1 when the output was truncated.
`

https://github.com/CroatiaControlLtd/asterix/blob/8802d9b13f0f26eb7e126445d0dda403c6aef065/src/asterix/Utils.cpp#L41

https://github.com/CroatiaControlLtd/asterix/blob/8802d9b13f0f26eb7e126445d0dda403c6aef065/src/asterix/Utils.cpp#L29

**Comment by dsalantic** [comment]
Thanks, I think I fixed this even for glibc < 2.0.6
