### ISSUE TITLE
decoding from stdin corrupts datarecords

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#130]
I'm totally lost with the following problem, after several days of inspecting the code, I'm unable to know why this is happening. Using the latest version pulled from github (asterix_r is the release version, asterix_d is the debug version).

This works:
asterix_r -d conf/asterix.ini -LF filter.ini -f file.ast -j
cat file.ast | asterix_r -d conf/asterix.ini -LF filter.ini -j
zcat file.ast.gz | ./asterix_r -d conf/asterix.ini -LF filter.ini -j > /dev/null
bzcat file.ast.bz2 | asterix_d -d conf/asterix.ini -LF filter.ini -j
bzcat file.ast.bz2 | valgrind asterix_r -d conf/asterix.ini -LF filter.ini -j

While this doesn't:
bzcat file.ast.bz2 | asterix_r -d conf/asterix.ini -LF filter.ini -j
ERROR:   Jun  1 23:59:01 2020 (asterixformat.cxx) DataItem format not defined for CAT002/I
ERROR:   Jun  1 23:59:01 2020 (asterixformat.cxx) Data Record bytes: [ DB 48 20 01 00 00 00 30 A2 00 00 40 00 05 05 CD AA 83 46 20 E0 02 00 08 E0 68 01 02 A0 30 00 1B F3 17 40 14 01 3F 1F 64 20 04 18 27 1E 18 04 39 01 AB ...

~~~
# cat filter.ini
CAT002:I010:SAC                                              System Area Code
CAT002:I010:SIC                                              System Identification Code
CAT034:I010:SAC                                              System Area Code
CAT034:I010:SIC                                              System Identification Code
CAT048:I010:SAC                                              System Area Code
CAT048:I010:SIC                                              System Identification Code
~~~

~~~
# cat conf/asterix.ini
asterix_bds.xml
asterix_cat001_1_2.xml
asterix_cat002_1_0.xml
asterix_cat034_1_27.xml
asterix_cat048_1_21.xml
~~~

Looks like reading from a bzip2 decompressed output somehow doesn't work.

**Comment by dsalantic** [comment]
I couldn't reproduce the problem. Can you provide sample file.ast file ?

**Comment by ifsnop** [comment]
[file.ast.bz2](https://wetransfer.com/downloads/85249f5637adc2297fc1950b75e7afbb20200602085012/80e01a74fb00f5bdad81a1879518760620200602085040/1e2f04)

**Comment by dsalantic** [comment]
OK, I downloaded sample and tried it, but I can't reproduce the problem.
Are you sure that you didn't specific -F instead of -LF ? When I do that I get similar output.

**Comment by ifsnop** [comment]
When I execute the offending combination of options:
bzcat file.ast.bz2 | asterix_r -d conf/asterix.ini -LF filter.ini -j

I get errors decoding the asterix file. It doesn't make sense, since the file decodes ok using other options. I could reproduce the problem compiling asterix in other machines, so somehow the problem is when using stdin as input and filtering. I have inserted debug info, and saw that in some point, datarecord decoded is not the datarecord dumped by bzcat (crc doesn't match), and then decoder errors. I have used tee, to check if decompression is ok:, 

bzcat file.ast.bz2 | tee test.ast | asterix_r -d conf/asterix.ini -LF filter.ini -j

And of coruse it is ok.

Have you tried:

bzcat file.ast.bz2 | asterix_r -d conf/asterix.ini -LF filter.ini -j > /dev/null

And see if there is any error reported?

**Comment by dsalantic** [comment]
OK, I reproduced it with your filter.ini.
Strange bug, but I'll try to find it.

**Comment by dsalantic** [comment]
It was a bug in stdin reading. It seems that bzcat is not fast enough for asterix and it happened that it didn't return complete packet, but just part of it and asterix  didn't handle it properly.
Please try and confirm if it is OK now.
Thanks

**Comment by acebrianjuan** [comment]
Hi folks,

I pulled the latest version and I can't reproduce the bug.
The decoder works fine for me without any ERROR messages. Just an INFO message when reaching the end of the file.

```
$ bzcat file.ast.bz2 | ./asterix -d ./config/asterix.ini -LF filter.ini -j > /dev/null
INFO:    Jun  3 13:37:34 2020 (/home/alvaro/git/asterix/src/engine/converterengine.cxx) No more data available on input channel.
```

Regards,
Álvaro

**Comment by acebrianjuan** [comment]
I edited my comment to clarify the version of the decoder I was using to avoid potential confusion with Damir's latest commit https://github.com/CroatiaControlLtd/asterix/commit/191b375b2212f31f9131de50630dc75d3a4bec0f.

Regards,
Álvaro

**Comment by ifsnop** [comment]
Alvaro, seems that your computer is fast enough and can keep up with decoding. The patch from @dsalantic fixes the problem for me.

Also, the patch makes a lot of sense. I did lots of tests, but didn't spot it.

@dsalantic , take several 🍺 !
