### ISSUE TITLE
Implement extensive JSON output format

### ISSUE THREAD

**Issue by dsalantic** [CroatiaControlLtd/asterix#135]
New format should contain hexadecimal presentation of items:

"CAT048":{
	"I010":{
		"SAC":{"val"=25, "hex"="19", "name"="System Area Code"},
		"SIC":{"val"=201, "hex"="C9", "name"="System Identification Code"}},
	"I140":{
		"ToD":{"val"=27354.6015625, "hex"="356D4D", "name"="Time Of Day"}},
	"I020":{
		"TYP":{"val"=5, "hex"="05", "name"="TYP", "meaning"="Single ModeS Roll-Call"},
		"SIM":{"val"=0, "hex"="00", "name"="SIM", "meaning"="Actual target report"},
		"RDP":{"val"=0, "hex"="00", "name"="RDP", "meaning"="Report from RDP Chain 1"},
		"SPI":{"val"=0, "hex"="00", "name"="SPI", "meaning"="Absence of SPI"},
		"RAB":{"val"=0, "hex"="00", "name"="RAB", "meaning"="Report from aircraft transponder"},
		"FX":{"val"=0, "hex"="00", "name"="FX", "meaning"="End of Data Item"}},

**Comment by dsalantic** [comment]
First quick implementation is in branch extensive_json_format 
Anyone interested, please check.

**Comment by ifsnop** [comment]
Main usage for me is to be able to locate where in the hexdata string, are the bytes we are decoding. The way this is implemented, this only work for dataitems which haven't got bit fields.

I020/TYP can't be found in hexdata because you are printing the string in hex after decomposing the multibit structure. It should be printed before decoding, so I020/TUP should be "A0", and the same for I020/SIM, I020/RDP... etc. If FX=1, then the following byte should be printed.

Does this makes sense to you? Currently, now the program is printing the hex conversion of the val value (after adjusting with the lsb), whereas I was looking for the original hex byte/s.

~~~
"hexdata":"30003FFFFF02140A1C20CCA0A25A36EC02790640E00902BF44CCC5085331CF0D2002CE200030AA00004087C9E7322004006008324F2B11EE088E103A4620FD",
"CAT048":{
        "I010":{
                "SAC":{"val"=20, "hex"="14", "name"="System Area Code"},
                "SIC":{"val"=10, "hex"="0A", "name"="System Identification Code"}},
        "I140":{
                "ToD":{"val"=14401.5937500, "hex"="1C20CC", "name"="Time Of Day"}},
        "I020":{
                "TYP":{"val"=5, "hex"="05", "name"="TYP", "meaning"="Single ModeS Roll-Call"},
                "SIM":{"val"=0, "hex"="00", "name"="SIM", "meaning"="Actual target report"},
                "RDP":{"val"=0, "hex"="00", "name"="RDP", "meaning"="Report from RDP Chain 1"},
                "SPI":{"val"=0, "hex"="00", "name"="SPI", "meaning"="Absence of SPI"},
                "RAB":{"val"=0, "hex"="00", "name"="RAB", "meaning"="Report from aircraft transponder"},
                "FX":{"val"=0, "hex"="00", "name"="FX", "meaning"="End of Data Item"}},
        "I040":{
                "RHO":{"val"=162.3515625, "hex"="A25A", "name"="RHO"},
                "THETA":{"val"=77.2338867, "hex"="36EC", "name"="THETA"}},
~~~

**Comment by dsalantic** [comment]
OK I understand. Now I modified it to show relevant bytes in hex and also a bit mask in case that it's not full byte. 
Please check:

`
 "hexdata": 
"300030FDF70219C9356D4DA0C5AFF1E0020005283C660C10C236D4182001C0780031BC0000400DEB07B9582E410020F5", 
"CAT048":{

    "I010":{
       "SAC":{"val"=25, "hex"="19", "name"="System Area Code"},
        "SIC":{"val"=201, "hex"="C9", "name"="System Identification Code"}},
    "I140":{
        "ToD":{"val"=27354.6015625, "hex"="356D4D", "name"="Time Of Day"}},
    "I020":{
        "TYP":{"val"=5, "hex"="A0"", "mask"="11100000", "name"="TYP", "meaning"="Single ModeS Roll-Call"},
        "SIM":{"val"=0, "hex"="A0"", "mask"="00010000", "name"="SIM", "meaning"="Actual target report"},
        "RDP":{"val"=0, "hex"="A0"", "mask"="00001000", "name"="RDP", "meaning"="Report from RDP Chain 1"},
        "SPI":{"val"=0, "hex"="A0"", "mask"="00000100", "name"="SPI", "meaning"="Absence of SPI"},
        "RAB":{"val"=0, "hex"="A0"", "mask"="00000010", "name"="RAB", "meaning"="Report from aircraft transponder"},
        "FX":{"val"=0, "hex"="A0"", "mask"="00000001", "name"="FX", "meaning"="End of Data Item"}},
    "I040":{
        "RHO":{"val"=197.6835938, "hex"="C5AF", "name"="RHO"},
        "THETA":{"val"=340.1367188, "hex"="F1E0", "name"="THETA"}},
    "I070":{
        "V":{"val"=0, "hex"="02"", "mask"="10000000", "name"="V", "meaning"="Code validated"},
        "G":{"val"=0, "hex"="02"", "mask"="01000000", "name"="G", "meaning"="Default"},
        "L":{"val"=0, "hex"="02"", "mask"="00100000", "name"="L", "meaning"="Mode-3/A code as derived from the reply of the transponder"},
        "spare":{"val"=0, "hex"="02"", "mask"="00010000", "name"="spare bit set to 0"},
        "Mode3A":{"val"="1000", "hex"="0200"", "mask"="0000111111111111"", "name"="Mode-3/A reply code"}},

`

**Comment by ifsnop** [comment]
This is perfect. Just let me use it some more time, to be sure it covers all my use cases.

**Comment by ifsnop** [comment]
Just to note, there is a double " after some hex definitions (when it is inside a multibit dataitem)

**Comment by dsalantic** [comment]
OK, I fixed that and merged changes to master. If you find any problems let me know.
