### ISSUE TITLE
Problem decoding Range Exceeded Indicator (RE) in I021/160

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#146]
Range Exceeded Indicator (RE) in I021/160 doesn't seem to be decoding the correct bit.  Looking at config files, RE is assigned bit 16.  I believe this should be bit 32 instead.  The issue is found in these config files:
install/config/asterix_cat021_2_4.xml
install/config/asterix_cat021_2_1_RE_1_1.xml
install/config/asterix_cat021_1_8.xml

**Comment by dsalantic** [comment]
corrected
