### ISSUE TITLE
Skip block with invalid length

### ISSUE THREAD

**Issue by bbertrand** [CroatiaControlLtd/asterix#15]
We have some asterix recordings in final format with a missing byte from time to time.

Running `asterix  -d /etc/asterix/asterix.ini -F -f missing_byte.ff -j` gives:

```
{"timestamp":4244580,"CAT002":{"I010":{"SAC":64,"SIC":11},"I000":{"type":2},"I020":{"Azi":112.5000000},"I030":{"ToD":4243.6093750}}},
ERROR:   Sep 16 09:21:56 2015 (asterixformat.cxx) Wrong Asterix data length (11)
ERROR:   Sep 16 09:21:56 2015 (asterixformat.cxx) DataItem::parse needed length=3 , and there is only 2
ERROR:   Sep 16 09:21:56 2015 (asterixformat.cxx) Wrong length in DataItem format for CAT002/I030
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
```

Indead, using recview, it's easy to see that one byte is missing at 01:10:44,76:
```
L10 E00 T01:10:44,58 ->  0200 0BF0 400B 0250 0849 CE
L10 E00 T01:10:44,76 ->  0200 0BF0 400B 0208 49E6
L10 E00 T01:10:44,95 ->  0200 0BF0 400B 0260 0849 FE
```

It would be nice if asterix could just skip the invalid block and continue the parsing instead of crashing.

Final format file with missing byte: https://www.dropbox.com/s/inft659zmhkn5yb/missing_byte.ff?dl=0
Same file decoded in hexa:  https://www.dropbox.com/s/2znv584x1h03bi5/missing_byte.hex?dl=0

**Comment by dsalantic** [comment]
Should be fixed now.

**Comment by bbertrand** [comment]
Thanks for the quick fix!
