### ISSUE TITLE
Scale does not match the spec for I062/380, subfield #22 (Position)

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#151]
For latitude and longitude in I062/380 subfield #22 (Position), LSB is defined in the spec as 180/2^23 or 0.000021457672119140625 degrees.  However, in config files lat and lon are scaled by 0.00000536441802978515625.  The issue is present in:
install/config/asterix_cat062_1_16.xml
install/config/asterix_cat062_1_17.xml
install/config/asterix_cat062_1_18.xml

**Comment by dsalantic** [comment]
I fixed it. Thank you for your contribution.

**Comment by tmartincevic** [comment]
Thank you for the quick fixes.
