### ISSUE TITLE
Problem decoding Runway Designation in I062/390

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#153]
The First number (NU1) and Letter (LTR) fields seem to be swapped when decoding I062/390, subfield # 9 (Runway Designation).  I get

`Item 390 : Flight Plan Related Data
[ 01 40 32 35 4C ]
        First number: L
        Second number: 5
        Letter: 2`

but as per spec I would expect

`Item 390 : Flight Plan Related Data
[ 01 40 32 35 4C ]
        First number: 2
        Second number: 5
        Letter: L`

**Comment by dsalantic** [comment]
It looks good in XML definition.
Can you share the asterix packet with which I can reproduce it ?

**Comment by tmartincevic** [comment]
Never mind, I figured it out.  Here is the packet capture:

[issue-153.zip](https://github.com/CroatiaControlLtd/asterix/files/5124353/issue-153.zip)

**Comment by princepaul** [comment]
Possible Fix: Modify asterix_cat062_1_18.xml - Lines 2722 to 2735

                <Fixed length="3">
                    <Bits from="1" to="8" encode="ascii">
                        <BitsShortName>NU1</BitsShortName>
                        <BitsName>First number</BitsName>
                    </Bits>
                    <Bits from="9" to="16" encode="ascii">
                        <BitsShortName>NU2</BitsShortName>
                        <BitsName>Second number</BitsName>
                    </Bits>
                    <Bits from="17" to="24" encode="ascii">
                        <BitsShortName>LTR</BitsShortName>
                        <BitsName>Letter</BitsName>
                    </Bits>
                </Fixed>

**Comment by dsalantic** [comment]
Thank you for your report and the sample. It was a bug in ASCII decoding. Now it is fixed and new version is created.
