### ISSUE TITLE
Scale does not match the spec for I062/500, subfield # 3

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#154]
For I062/500, subfield # 3 (Estimated Accuracy Of Track Position (WGS-84)), fields APW_Lat and APW_Long are scaled by 0.000021457672119140625.  As per spec, LSB for these two fields is 180/2^25 or 0.00000536441802978515625.  The issue is present in:
install/config/asterix_cat062_1_16.xml
install/config/asterix_cat062_1_17.xml
install/config/asterix_cat062_1_18.xml

**Comment by dsalantic** [comment]
Fixed
