### ISSUE TITLE
Scale does not match the spec for I062/500, subfield # 5

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#155]
For I062/500, subfield # 5 (Estimated Accuracy Of Calculated Track Barometric Altitude), ABA_Acc is scaled by 6.25 ft.  As per spec, LSB for this field is 1/4 FL or 25 ft. The issue is present in:
install/config/asterix_cat062_1_16.xml
install/config/asterix_cat062_1_17.xml
install/config/asterix_cat062_1_18.xml

**Comment by dsalantic** [comment]
Fixed
