### ISSUE TITLE
I048/200 and I048/210 use approximate value to scale groundspeed

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#158]
Both I048/200 CGS (Calculated groundspeed) and I048/210 SigmaV (Sigma Groundspeed) use the approximate scale factor of 0.22 kt.  For consistency, should this be replaced with the actual value from the spec which is 2^-14  NM/s or 2^-14 * 3600 kt or 0.2197265625 kt?
Other fields in these data items use exact values from the spec.  For example, in I048/200 CHdg the scale is 0.0054931640625 rather than approximate 0.0055.  Similar for I048/210 SigmaH where the scale is 0.087890625 rather than approximate 0.08789.
Applies to install/config/asterix_cat048_1_14.xml and install/config/asterix_cat048_1_21.xml.

**Comment by dsalantic** [comment]
Thanks again for you fix.
