### ISSUE TITLE
Issue with enforcement of fx=1

### ISSUE THREAD

**Issue by koutcher** [CroatiaControlLtd/asterix#16]
When Variable type is used, there is a check that all items end with an FX bit. 

In I021/271, only the Primary Subfield has an FX bit, the bit 1 in first extension is used to encode Length / Width of Aircraft.
This is not a mistake as it is explicitly described in a note:
NOTE - This data item is a variant of the “Extended length data field” as
described in ASTERIX part1. The LSB in the first extension is not
used as FX-bit.

The current XML description of cat 021 follows the standard and the file is rejected because of the check on fx=1.

**Comment by dsalantic** [comment]
OK, I see the problem. 
It can be fixed, but I would appreciate if you could submit an example of recording that contains this format. 
Thanks

**Comment by koutcher** [comment]
Hi,

please find attached 30s of ADS-B traffic simulated with PTG. Here is 
the error you get when you use asterix_cat021_1_8.xml:

Missing fx=1 in primary part of Variable item. in file: 
/usr/share/ethereal/asterix/asterix_cat021_1_8.xml line: 1193

Failed to parse definitions file: 
/usr/share/ethereal/asterix/asterix_cat021_1_8.xml

Opened asterix.log file

Failed to initialize Asterix plugin (10545880)

Kind regards,
Thomas

**Comment by dsalantic** [comment]
Hi Thomas,

I don't see attachment. Please put a link to Dropbox.
Damir

**Comment by dsalantic** [comment]
I put a workaround for this issue.
Simply you can use one of the spare bits (which must be 0) to server as fx bit.

**Comment by koutcher** [comment]
Good idea. At least until EC decides to use the spare bits. 

Did you stop tagging releases after V2.1.0 ?

**Comment by dsalantic** [comment]
I'll keep this issue open, until I find time to fix it.
I just tagged V2.1.4 (including CAT012 workaround).

**Comment by ifsnop** [comment]
Hi there,

Great job, this tool is really useful. Just my 0.01 eurocents:

Instead of using the spare bits (which are at the begining of the byte) maybe you could simply disable the check for a fx bit in the variable type. Defining a new type of <variable_without_fx> is a bit overkill.

**Comment by dsalantic** [comment]
Thank you all for your contribution.
Now we do not check for fx bit any more because there are some formats that  do not have fx bit in primary part of variable item (e.g. I021/271).
Now if the fx is not defined it means that this is the last primary field.
