### ISSUE TITLE
CAT021 - problem decoding Military Extended Squitter in Reserved Expansion Field

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#161]
Using install/config/asterix_cat021_2_4.xml.  Trying to decode Mode 5 Summary in Military Extended Squitter, Reserved Expansion Field does not produce expected output.  There are several issues in the RE section of the config file.  Network capture as well as updated config file are attached.
```
-------------------------
Data Block 1
Category: 21
Len: 13
-------------------------
Data Record 1
Len: 13
CRC: 80D4EFBB
Timestamp: 52888414
HexData: 15001081010101010104D27D04018081

Item 010 : Data Source Identification
[ D2 7D ]
        System Area Code: 210
        System Identification Code: 125

Item RE : Reserved Expansion Field
[ 04 01 80 81 ]
        Spare bits set to zero: 8
        Warning: Value should be set to 0
        Barometric Pressure Setting: 264 (26.4000000 mb)
        Spare bits set to zero: 0
        Barometric Pressure Setting: 2048 (204.8000000 mb)
```
[021-re-mes-sum.zip](https://github.com/CroatiaControlLtd/asterix/files/5219349/021-re-mes-sum.zip)
[asterix_cat021_2_4.zip](https://github.com/CroatiaControlLtd/asterix/files/5219975/asterix_cat021_2_4.zip)

**Comment by tmartincevic** [comment]
More updates to config file (ignore the one from the original post):
[asterix_cat021_2_4.zip](https://github.com/CroatiaControlLtd/asterix/files/5220814/asterix_cat021_2_4.zip)

**Comment by dsalantic** [comment]
Thanks for your fix. I merged your changes except the SelHHRD to HRD item rename, because HRD already exists in same category.

**Comment by tmartincevic** [comment]
Thank you for catching the duplicate name.
