### ISSUE TITLE
Scale missing from Mode 5 GNSS-derived Altitude in I062/110

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#166]
Is there any particular reason why GNSS-derived Altitude (GA) in subfield 4 of I062/110 is not scaled?  As per notes in the spec:

*GA is coded as a 14-bit two’s complement binary number with an LSB of 25 ft. irrespective of the setting of RES.*
*The minimum value of GA that can be reported is -1000 ft.*

Suggest adding scale, minimum and unit to GA.  Proposed changes and a sample message capture are attached.
[062-110-GA.zip](https://github.com/CroatiaControlLtd/asterix/files/5456509/062-110-GA.zip)

**Comment by dsalantic** [comment]
You are right. It's fixed now.
Thanks
