### ISSUE TITLE
Subfield 8 of I062/380 (Trajectory Intent Status) should be defined as Variable in xml config

### ISSUE THREAD

**Issue by tmartincevic** [CroatiaControlLtd/asterix#167]
Subfield 8 of I062/380 (Trajectory Intent Status) should be defined as Variable as per ASTERIX spec and similar to subfield 1 of I021/110.  It's currently defined as Fixed and this produces inconsistent JSON output when compared to I021/110.  As per #162, TIS is wrapped in a list for I021/110:
```json
"CAT021":{
        "I010":{
                "SAC":210,
                "SIC":125},
        "I110":{
                "TIS":[{
                "NAV":1,
                "NVB":1,
                "spare":0,
                "FX":0}]}}},
```
But for I062/380 there is no list for TIS since it is not declared as Variable:
```json
"CAT062":{
        "I010":{
                "SAC":210,
                "SIC":125},
        "I380":{
                "TIS":{
                "NAV":1,
                "NVB":1,
                "spare":0,
                "FX":0}}}},
```
Packet captures and proposed change: 
[062-380-TIS.zip](https://github.com/CroatiaControlLtd/asterix/files/5486216/062-380-TIS.zip)

If this change is accepted, it might be good to add I062/380 to the existing list of affected data items in HISTORY.

**Comment by dsalantic** [comment]
OK, accepted. Tnx
