### ISSUE TITLE
error codes from write are not detected

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#168]
Detecting when parsing asterix output with pipes.

engine/stddevice.cxx:76 

~~~
size_t bytesWrote = write(STDOUT_FILENO, pData, bytesLeft);
if (bytesWrote < 0) {
~~~

In  case of error when writing, code path won't enter inside "if", because size_t is not signed, and errors from write are returned with -1

The error that bite me was EPIPE, when writing to a closed pipe.

Please replace size_t with ssize_t

Same error is also inside engine/serialdevice.cxx

**Comment by dsalantic** [comment]
OK, done. tnx
