### ISSUE TITLE
minor erroe found in asterix_cat010_1_1.xml

### ISSUE THREAD

**Issue by imromero** [CroatiaControlLtd/asterix#17]
I have found a wrong parameter in asterix_cat010_1_.xml

The data item 41 (Position in WGS-84 Coordinates) has a scale factor for both latitude and longitude of 0.000005364418029785156.

The Eurocontrol Specifications say that this scale must be 180/2^31. So, the scale factor must be 0,00000008381903171539306640625.

I made some tests with asterix cat 010 with a Southampton port radar and with this new value, the software seems to work fine and the final coordinates are correct.

Thanks a lot
Nacho

**Comment by dsalantic** [comment]
Thanks. It is fixed now.
