### ISSUE TITLE
Cat021 Ed2.4 SelH is not reasonable

### ISSUE THREAD

**Issue by nunojpg** [CroatiaControlLtd/asterix#175]
https://github.com/CroatiaControlLtd/asterix/blob/2c8f320ea053231abd671ad44d50971fcba8a625/install/config/asterix_cat021_2_4.xml#L1762

A 10 bit field with 0.703125 LSB allows for 0 to 720º.

I understand this is the exact description on the latest spec (EUROCONTROL-SPEC-0149-12-A), but it just does not make sense.

Instead Eurocae ED-129B says this field is a 9 bit signed value, which makes it -180 to 180. The 2 MSbs are so always equal.

What is the way here? Keeping it useless according to spec of fixing it a la carte?

**Comment by dsalantic** [comment]
You are right. It should be signed. Specification is not clear because it doesn't say it is in two's complement, but it doesn't it is isn't either.
So, I fixed it.
