### ISSUE TITLE
Parse udp data from multicast stream

### ISSUE THREAD

**Issue by wsinbol** [CroatiaControlLtd/asterix#177]
I had some problems.
I want to parse udp data from multicast stream. According to the tutorial, 

```

Data source
------------
        -f filename     File generated from libpcap (tcpdump or Wireshark) or file in FINAL or HDLC format.
                        For example: -f filename.pcap
        -i m:i:p[:s]    Multicast UDP/IP address:Interface address:Port[:Source address].
                        For example: 232.1.1.12:10.17.58.37:21112:10.17.22.23
                        More than one multicast group could be defined, use @ as separator.
                        For example: 232.1.1.13:10.17.58.37:21112:10.17.22.23@232.1.1.14:10.17.58.37:21112:10.17.22.23
```

I execute the command on CentOS:

```
./asterix -i 192.168.10.37:192.168.10.38:8080 (just an example)
```

The address of network are provided by a Network Engineer of my company. And I think it's correct.But I got the results like this:

```
ERROR:   Jan 11 14:13:52 2021 (udpdevice.cxx) Cannot bind port number 8080
ERROR:   Jan 11 14:13:52 2021 (udpdevice.cxx) Server not initialized
ERROR:   Jan 11 14:13:52 2021 (channelfactory.cxx) Couldn't create device 'udp'.
ERROR:   Jan 11 14:13:52 2021 (converterengine.cxx) Input channel initialization failed.
ERROR:   Jan 11 14:13:52 2021 (asterix.cpp) Couldn't initialize asterix engine.
```

I have tried many other ways such as replaceing the position of network address, and it still didn't work. Can someone tell me what the problem is?Looking forward to receiving a reply.Thanks.

**Comment by ifsnop** [comment]
By the error msg, maybe the port is already in use. Could you just try with another port number? Application won't work, but at least you can rule out asterix as the source of the problem, and search (and stop) the other app that is using the port.

**Comment by mustafacil** [comment]
hello @wsinbol, how many network interfaces has the computer?
