### ISSUE TITLE
created CAT021 V0.23 and CAT247 V1.2

### ISSUE THREAD

**Issue by junglejet** [CroatiaControlLtd/asterix#18]
please accept contribution of two XML files
renamed .txt to be able to upload them here
thank you for all your hard work
andy

[asterix_cat247_1_2.xml.txt](https://github.com/CroatiaControlLtd/asterix/files/46404/asterix_cat247_1_2.xml.txt)
[asterix_cat021_0_23.xml.txt](https://github.com/CroatiaControlLtd/asterix/files/46405/asterix_cat021_0_23.xml.txt)

**Comment by dsalantic** [comment]
Hi Andy, thank you for your contribution.
I included your file to repository.
