### ISSUE TITLE
asterix_cat034_1_26.xml: Data item 050 SSR status: bit 4 read twice

### ISSUE THREAD

**Issue by hubbiedihub** [CroatiaControlLtd/asterix#20]
Parsing the bit 4 "OVL RDP" is not correct as not part of the standard.

Proposal remove first Bit element: Change this:
`<Bits bit="4">`
`	<BitsShortName>OVL RDP</BitsShortName>`
`        <BitsName>OVL RDP</BitsName>`
`	<BitsValue val="1">Overload in RDP</BitsValue>`
`        <BitsValue val="0">No overload</BitsValue>`
`</Bits>`
`<Bits bit="4">`
`	<BitsShortName>MSC</BitsShortName>`
`        <BitsName>MSC</BitsName>`
`	<BitsValue val="1">Monitoring system disconnected</BitsValue>`
`        <BitsValue val="0">Monitoring system connected</BitsValue>`
`</Bits>`

to 

`<Bits bit="4">`
`	<BitsShortName>MSC</BitsShortName>`
`        <BitsName>MSC</BitsName>`
`	<BitsValue val="1">Monitoring system disconnected</BitsValue>`
`        <BitsValue val="0">Monitoring system connected</BitsValue>`
`</Bits>`

**Comment by dsalantic** [comment]
It has been fixed. Thank you for your contribution.
