### ISSUE TITLE
examples fail on macOS 12 (M1) with python 3.9.10 fail

### ISSUE THREAD

**Issue by paulmadejong** [CroatiaControlLtd/asterix#206]
Using Asterix version 0.7.3, installed through pip. Both the python test `read_raw_file.py` and `read_raw_bytes.py` fail with the following error:
``
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/asterix/examples/read_raw_bytes.py", line 17, in <module>
    formatted = asterix.describe(parsed)
  File "/opt/homebrew/lib/python3.9/site-packages/asterix/__init__.py", line 255, in describe
    strts = datetime.fromtimestamp(ts / 1000.)
ValueError: year 151778444 is out of range
``

The test `read_final_file.py` cannot be run since it references a hardcoded path to a sample file not provided in this repo.

Also, using the same logic as the `read_raw_file.py` example to read an *.ast file from MUAC (CAT048) does not seem to work whereas other tools do read this type of data. I cannot find documentation on this library so perhaps I am missing something?

**Comment by dsalantic** [comment]
It should be fixed in latest release. Please try.
