### ISSUE TITLE
FX field doesn't seem to be decoded correctly on CAT 048/170 (Track Status)

### ISSUE THREAD

**Issue by mitch40** [CroatiaControlLtd/asterix#216]
When I decode the packet contained in the pcap file provided as an attachment, 

I note that the "FX" field of dataitem 170 (Track Status) does not seem to be decoded correctly. 
In wireshark we can see that the value of this field is "1", which is logical since there is other data after FX.

However in the json generated by the decoder the value of the FX field is 0.
![cat_048_json](https://github.com/CroatiaControlLtd/asterix/assets/48313048/cb337de7-fd75-48e9-a6bc-f56c240b6e71)
![cat_048_wireshark](https://github.com/CroatiaControlLtd/asterix/assets/48313048/b3a0ad69-e416-450e-a0d8-2ace9b5603c0)

**Comment by mitch40** [comment]
if you need pcap file i cannot upload it on github, so it's available here : https://gofile.io/d/mi6gwx

**Comment by dsalantic** [comment]
@mitch40 If this problem is still relevant please resend the sample data.
I couldn't reproduce it.
