### ISSUE TITLE
cygwin 

### ISSUE THREAD

**Issue by Eldenayri** [CroatiaControlLtd/asterix#218]
I ran this program on Linux without any problems, and now i am trying open it on windows via cygwin.  i installed on cygwin : binutils, cygwin-devel, gcc-core, gcc-g++, make, libexpat-devel, python-pip-wheel, python-setuptools-wheel, python3, python3-devel, python38-pip, python38-wheel and i ran via cygwin "pip install asterix_decoder" 

 4E@DESKTOP-SEOIF7U ~
$ pip install asterix_decoder --user
Collecting asterix_decoder
  Using cached asterix_decoder-0.7.4.tar.gz (253 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: asterix_decoder
  Building wheel for asterix_decoder (setup.py) ... done
  Created wheel for asterix_decoder: filename=asterix_decoder-0.7.4-cp39-cp39-cygwin_3_4_9_x86_64.whl size=1183056 sha256=76ccd77f49b7a419c2efcb442816feff5f41fa69285e70dc02c27561a9b44977
  Stored in directory: /home/4E/.cache/pip/wheels/81/21/af/3c38bdb83bcef0c108907240c2fa244a83c87a4762c02bad74
Successfully built asterix_decoder
Installing collected packages: asterix_decoder
Successfully installed asterix_decoder-0.7.4

What should I do to open it on Pycharm? There is no setup.py file. What is next?

**Comment by dsalantic** [comment]
Just import asterix module and use it in your python code.
See some examples here: https://github.com/CroatiaControlLtd/asterix/tree/master/asterix/examples
