### ISSUE TITLE
Transform .ast file to csv

### ISSUE THREAD

**Issue by marius190** [CroatiaControlLtd/asterix#219]
Hi,

I have two ASTERIX  ".ast" files containing categories 21 and 48 information. Is it possible to convert the .ast files to a .csv file for instance?

How can I open the .ast file and understand the data structure, so I can transform it in any other format by myself?

Thank you very much!

Marius

**Comment by dsalantic** [comment]
You need to implement a python application that will parse each packet from your ast file. It will return data in dictionary and then you can write them to CSV file or any other format you want.
