### ISSUE TITLE
Memory leak in parse_with_offset python function

### ISSUE THREAD

**Issue by rrhtgmv** [CroatiaControlLtd/asterix#231]
Each time the parse_with_offset() function is called, the memory consumed by the program increases, even if the result of the function is never stored. 
The memory increment seems proportional to the number of blocks decoded, e.g. calling parse_with_offset(data,0,100) increases consumed memory less than calling parse_with_offset(data,0,1000).

Using library installed via pip with version 0.7.6 (pip install asterix_decoder==0.7.6), on a docker container from image python:3.12-alpine.

Example code to reproduce the issue:

> ```
> import asterix
> 
> with open('file.ast', 'rb') as f:
>     data = f.read()
> 
> for i in range(10):
>     asterix.parse_with_offset(data,0,100)
> ```

Each time the line with the parse_with_offset() function is executed, the memory consumed by the program increases, even though the result is not being stored.

Also found useful the library memory-profiler to check the memory consumption of the program and the line where more memory was being increased.

**Comment by dsalantic** [comment]
@rrhtgmv Thanks for your input. Can you write a simple script how to prove that there is a memory leak (e.g. using the memory_profiler) ?

**Comment by rrhtgmv** [comment]
Hi, the following script can be used to check the memory consumption:

> ```
> import asterix
> from memory_profiler import profile
> 
> @profile
> def func(data):
>     asterix.parse_with_offset(data, 0, 100)
> 
> if __name__ == '__main__':
>     with open('example.ast', 'rb') as f:
>         data = f.read()
> 
>     for i in range(10):
>         func(data)
> ```

As you can see, the profiled function `func` only calls the `parse_with_offset` method and does not store the result, so the memory it uses should be freed when returning from the call. However, the profiler output shows that the consumed memory is increased every time this call is executed and is never freed, causing the total memory consumed by the program to keep increasing. Some of the output from the execution of this script is:

> ```
> Filename: example.py
> Line #    Mem usage    Increment  Occurrences   Line Contents
> =============================================================
>      4     73.6 MiB     73.6 MiB           1   @profile
>      5                                         def func(data):
>      6     78.9 MiB      5.3 MiB           1       asterix.parse_with_offset(data, 0, 100)
> 
> Filename: example.py
> Line #    Mem usage    Increment  Occurrences   Line Contents
> =============================================================
>      4     78.9 MiB     78.9 MiB           1   @profile
>      5                                         def func(data):
>      6     84.2 MiB      5.3 MiB           1       asterix.parse_with_offset(data, 0, 100)
> 
> Filename: example.py
> Line #    Mem usage    Increment  Occurrences   Line Contents
> =============================================================
>      4     84.2 MiB     84.2 MiB           1   @profile
>      5                                         def func(data):
>      6     89.5 MiB      5.3 MiB           1       asterix.parse_with_offset(data, 0, 100)
> ```

Increasing (or decreasing) the number of blocks read in `parse_with_offset` results in more (or less) memory being consumed in each call. 
The number of times that is executed can also be changed (increasing the for loop range) to check that the memory keeps increasing until the program finishes or the OS kills it.

Thank you for your response, I hope this additional information is useful to discover what is exactly happening.

**Comment by dsalantic** [comment]
The problem was in missing Py_DECREF in python_parse_with_offset.
I created new version (0.7.7) with the fix.
Thank you very much for your help @rrhtgmv
