### ISSUE TITLE
When CAT48/250 is 0, no output is displayed

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#232]
With FSPEC "FF E1 02", "E1" means that I220, I240 and I250 are encoded. So, in the output, between I240 and I230 there should be I250, but because it is 00 (REP=0), it is not displayed in json/xml/human form.

``
{"id":1,"cat":48,"length":33,"crc":"F866D980","timestamp":1721207819.775935,"hexdata":"FFE102000037FB96A055BCC0660D1805EFE00002C33944F10464B7C944200020F5","CAT048":
{"I010":{"SAC":0,"SIC":0},"I140":{"ToD":28663.1718750},
"I020":{"TYP":5,"SIM":0,"RDP":0,"SPI":0,"RAB":0,"FX":0},
"I040":{"RHO":85.7343750,"THETA":270.5603027},"I070":{"V":0,"G":0,"L":0,"spare":0,"Mode3A":"6430"},
"I090":{"V":0,"G":0,"FL":379.7500000},
"I130":{"SRLP":{"SRL":0.0000000},"SRRP":{"SRR":2},"SAMP":{"SAM":-61.0000000}},
"I220":{"ACAddr":"3944F1"},
"I240":{"TId":"AFR72TP "},
"I230":{"COM":1,"STAT":0,"SI":0,"spare":0,"ModeSSSC":1,"ARC":1,"AIC":1,"BDS16":1,"BDS37":5}}}
``

To test, just make an asterix file with:
``
echo "30 00 24 FF E1 02 00 00 37 FB 96 A0 55 BC C0 66 0D 18 05 EF E0 00 02 C3 39 44 F1 04 64 B7 C9 44 20 00 20 F5" | xxd -r -p > output.ast
``

The important bytes are: 

... 44 F1 04 64 B7 C9 44 20 **00** 20 F5

This 00 is the corresponding to I250, which is not present in the output.

**Comment by dsalantic** [comment]
Hi @ifsnop , that was by design to not display the items with empty repetitive field. I'm not even sure if this is allowed by protocol to send empty item.
Anyway, I admit that this could be usefull to print it, to not leave gaps in displayed data, so I implemented it.
Please checkout  the commit above and test it.
Note: it is working for text and json outputs. For XML, it was already there.
I didn't implement it for python. I think it is not needed there.

**Comment by ifsnop** [comment]
> Hi @ifsnop <https://github.com/ifsnop> , that was by design to not
> display the items with empty repetitive field. I'm not even sure if this is
> allowed by protocol to send empty item.
> Anyway, I admit that this could be usefull to print it, to not leave gaps
> in displayed data, so I implemented it.
> Please checkout the commit above and test it.
> Note: it is working for text and json outputs. For XML, it was already
> there.
> I didn't implement it for python. I think it is not needed there.
>


Hi Damir,

You are right, rep items with count=0 are forbidden by the standard. But I
have found a bug in a sensor output that insists in filling bds dataitem
without checking if there is any to report, and most of the times it ends
sending rep 0.... So it is useful to have asterix reporting them, if not
reported there would be gaps and some byte would be unnoticed.

Thanks for the fix.

>
