### ISSUE TITLE
Memory not freed when asterix ends

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#25]
When running asterix within valgrind, there are some blocks that aren't correclty freed when exiting.

==2851== LEAK SUMMARY:
==2851==    definitely lost: 0 bytes in 0 blocks
==2851==    indirectly lost: 0 bytes in 0 blocks
==2851==      possibly lost: 412,850 bytes in 8,739 blocks
==2851==    still reachable: 598,628 bytes in 11,992 blocks
==2851==         suppressed: 0 bytes in 0 blocks

For example:

==2855== 7,973 bytes in 103 blocks are possibly lost in loss record 65 of 80
==2855==    at 0x4C286E7: operator new(unsigned long) (vg_replace_malloc.c:287)
==2855==    by 0x5118998: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17)
==2855==    by 0x5118B92: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17)
==2855==    by 0x5118D2B: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17)
==2855==    by 0x41C621: XMLParser::ElementHandlerStart(void*, char const*, char const**) (XMLParser.cpp:212)

Do you think this could be fixed?

**Comment by dsalantic** [comment]
Fixed
