### ISSUE TITLE
DataItem 110 "Height Measured by a 3D Radar": Height is signed not unsigned

### ISSUE THREAD

**Issue by hubbiedihub** [CroatiaControlLtd/asterix#34]
At least in version 1.21 of the CAT048 specification the DataItem 110 "Height Measured by a 3D Radar" is signed not unsigned: "3D height, in binary notation. Negative values are expressed in two’s complement."

So

`<Bits from="14" to="1">`

should be

`<Bits from="14" to="1" encode="signed">`

**Comment by dsalantic** [comment]
Corrected. Thanks.
