### ISSUE TITLE
Data Item I048/020, Target Report Descriptor: XPP missing

### ISSUE THREAD

**Issue by hubbiedihub** [CroatiaControlLtd/asterix#35]
At least in version 1.21 of the CAT048 specification the Data Item I048/020, Target Report Descriptor contains the XPP bit in the first extend. So

```xml
<Bits from="7" to="6">
	<BitsShortName>spare</BitsShortName>
	<BitsName>spare bits set to 0</BitsName>
	<BitsConst>0</BitsConst>                       
</Bits>
```

should be

```xml
<Bits bit="7">
	<BitsShortName>spare</BitsShortName>
	<BitsName>spare bit set to 0</BitsName>
	<BitsConst>0</BitsConst>                       
</Bits>
<Bits bit="6">
	<BitsShortName>XPP</BitsShortName>
	<BitsName>XPP</BitsName>
	<BitsValue val="0">No X-Pulse present</BitsValue>
	<BitsValue val="1">X-Pulse present</BitsValue>
</Bits>
```

**Comment by dsalantic** [comment]
Note that in source we have CAT048 version 1.14.
If you can prepare new file with all changes in v1.21, I can include it as new file.
Thanks

**Comment by hubbiedihub** [comment]
I simply copied the 1.14 file and added the XPP bit and updated the version/comments. Right now I'm not aware of additional changes for version 1.21:

[asterix_cat048_1_21.xml.zip](https://github.com/CroatiaControlLtd/asterix/files/195369/asterix_cat048_1_21.xml.zip)

**Comment by dsalantic** [comment]
Thanks, it is included in master branch now.
