### ISSUE TITLE
Additional updates for category 48, version 1.21

### ISSUE THREAD

**Issue by hubbiedihub** [CroatiaControlLtd/asterix#39]
Hi,
I stepped through the release notes and have now a version with hopefully all changes up to version 1.21 of category 48 attached. So you can replace the current one with this one.

[asterix_cat048_1_21.xml.zip](https://github.com/CroatiaControlLtd/asterix/files/234167/asterix_cat048_1_21.xml.zip)

**Comment by dsalantic** [comment]
Thanks. Included.
