### ISSUE TITLE
Example for reading Special Purpose field in CAT48

### ISSUE THREAD

**Issue by kentpachi** [CroatiaControlLtd/asterix#40]
Hello,

i'm looking for an example to read the Special Purpose field

in the xml its configured as following

```
<DataItem id="SP" >
		<DataItemName>Special Purpose Field</DataItemName>
		<DataItemDefinition>SP</DataItemDefinition>
		<DataItemFormat desc="Explicit">
			<Explicit>
					<Fixed length="1">
						<Bits from="8" to="1">
						<BitsShortName>SP</BitsShortName>
						<BitsName>SP</BitsName>
						</Bits>
					</Fixed>
				</Explicit>
		</DataItemFormat>
		<DataItemNote/>
	</DataItem>	
```	

I have a stream that contains a SP field but the parser is not able to show it up

the SP field content has variable length, the lenght is in the first octets

do you have any clue about how i can implement this "conditional" length using the xml definitions ?

thank you for help

**Comment by dsalantic** [comment]
Hi,

Explicit format has 1 byte for the length and then the payload of this length.
All you need to do is to define your format inside <explicit>, e.g.:

<Explicit>
   Your definition here (e.g. variable, fixed, compund etc.
</Explicit>

For more complicated examples see "RE" field in CAT004 or CAT020

**Comment by kentpachi** [comment]
Hello,

thank you for your response, its quite hard for me to start onto this as the RE field in CAT020 have a really huge définition

I have the following convention to implements can you give me some help about how to start . I'm lost between compound and repetitive as some bytes should repeats

The special purpose field will be of variable length depending on the number N of category-probability pairs. 
octet 0: unsigned 8 bit integer, representing the number of octets in the special purpose field including this octet, i.e. 2 + 2 * N octets in total.
octet 1: unsigned 8 bit integer, representing the number N of category-probability pairs.

For all pairs at index I from 0 to N-1:
octet (2+ 2*I): unsigned 8 bit integer, encoding the item category.
octet (2+ 2*I + 1): unsigned 8 bit integer, representing the probability for the advertised item category in percent (0 – 100).

For a single pair the message would be 4 bytes long, for two pairs 6, etc.

thanks for your help

**Comment by kentpachi** [comment]
I've started with this


```
	<DataItemFormat desc="Explicit">
                    <Explicit>
                        <Fixed length="1">
						<Bits from="8" to="1" encode="hex">
						<BitsShortName>O1</BitsShortName>						
							<BitsName>01LONG</BitsName>						
						</Bits>
			 </Fixed>
                      
                          <Fixed length="1">
						<Bits from="9" to="16" encode="hex">
						<BitsShortName>O2</BitsShortName>						
							<BitsName>O2LONG</BitsName>						
						</Bits>
			 </Fixed>
                                        
                            
                          <Fixed length="1">
						<Bits from="17" to="24" encode="hex">
						<BitsShortName>O3</BitsShortName>						
							<BitsName>O3LONG</BitsName>						
						</Bits>
			 </Fixed>
                                        
                                        
                                        
                                        
                                        
                          <Fixed length="1">
						<Bits from="15" to="32" encode="hex">
						<BitsShortName>O4</BitsShortName>						
							<BitsName>O4LONG</BitsName>						
						</Bits>
			  </Fixed>
                    </Explicit>
		</DataItemFormat>
```

**Comment by dsalantic** [comment]
I see. You format is actually Repetitive item inside Explicit.
Following should be correct definition:
```
 <DataItem id="SP" >
		<DataItemName>Special Purpose Field</DataItemName>
		<DataItemDefinition>SP</DataItemDefinition>
		<DataItemFormat desc="Explicit">
			<Explicit>
					<Repetitive>
						<Fixed length="2">
							<Bits from="16" to="9">
								<BitsShortName>CAT</BitsShortName>
								<BitsName>Category</BitsName>
							</Bits>
							<Bits from="8" to="1">
								<BitsShortName>PROB</BitsShortName>
								<BitsName>Probability</BitsName>
							</Bits>
						</Fixed>
					</Repetitive>
				</Explicit>
		</DataItemFormat>
		<DataItemNote/>
	</DataItem>
```

**Comment by kentpachi** [comment]
Thank you,

it says  ERROR:   May  3 17:18:31 2016 (asterixformat.cxx) Wrong length in Repetitive

i think i should add the first octets as fixed length something like but no success : 

 <DataItem id="SP" >
        <DataItemName>Special Purpose Field</DataItemName>
        <DataItemDefinition>SP</DataItemDefinition>
        <DataItemFormat desc="Explicit">
            <Explicit>
              <Fixed length="1">
                        <Bits from="8" to="1" encode="hex">
                        <BitsShortName>O1</BitsShortName>                       
                            <BitsName>01LONG</BitsName>                     
                        </Bits>
                    </Fixed>
                    <Repetitive>
                        <Fixed length="2">
                            <Bits from="16" to="9">
                                <BitsShortName>CAT</BitsShortName>
                                <BitsName>Category</BitsName>
                            </Bits>
                            <Bits from="8" to="1">
                                <BitsShortName>PROB</BitsShortName>
                                <BitsName>Probability</BitsName>
                            </Bits>
                        </Fixed>
                    </Repetitive>
                </Explicit>
        </DataItemFormat>
        <DataItemNote/>
    </DataItem>

**Comment by dsalantic** [comment]
What are the first 4 bytes in your SP field ?

**Comment by kentpachi** [comment]
it works like this 

A.  first byte  is un unsigned 8 bit integer representing the number of bytes in the SP field ( including the first one )

B. second one is an unsigned 8 bit integer as well representing the number of couple ( itemcat + item probability )

C. third is indicating item category

D. fourth is indicating item probability

this is the minimum for the SP field at least 4 bytes, so if there is only one pair of itemcategory+item probability, the sp field will be 4 bytes long, if there is two pairs it will be 6 bytes long 

we will always have at least AB then first cat will gives CD , second cat if present will give EF and so on

i hope its clear to understand :)

**Comment by dsalantic** [comment]
I understand the format, and I think the xml I sent you is correct.
Explicit format takes first byte.
Repetitive format takes second byte as number of repetitions and next 2 bytes are parsed as fixed.
My question was: What are the exact byte values from your sample? That way I can manually check where is the problem.
Tnx

**Comment by kentpachi** [comment]
ok not sure to undestand but i try ,

example  for 4 bytes ABCD

A  : 0000 0100
B :  0000 0001
C :  0001 0100
D :  0100 0110

A says  4 bytes in total
B says 1 pair 
C says  category value is 0x20
D says probability for item category is 70 

is that what you need ?

**Comment by dsalantic** [comment]
Is this just an example, or this is the real data you have in your sample that returns the error? 
Can you send me the data sample you are trying to parse?

**Comment by kentpachi** [comment]
Ok i have a sample file for you how can i send it to you via private msg or something ?

its an extract from a bigger file so parsing ends with some creepy errors but it will allow you to see the "repettive lenght" error with some true data

**Comment by dsalantic** [comment]
You can paste the sample here in github comment, or send it directly to me.
Thanks

**Comment by kentpachi** [comment]
here it is, the extension is txt for bypassing github but its binary

[sample1.txt](https://github.com/CroatiaControlLtd/asterix/files/248429/sample1.txt)

**Comment by dsalantic** [comment]
It works fine for me, see the output here:
[sample.txt](https://github.com/CroatiaControlLtd/asterix/files/248500/sample.txt)

I used this xml:

[asterix_cat048_1_21.xml.txt](https://github.com/CroatiaControlLtd/asterix/files/248504/asterix_cat048_1_21.xml.txt)

**Comment by dsalantic** [comment]
And please check that you are using the latest version of Asterix.
Note that there were lot of changes since you forked.

**Comment by kentpachi** [comment]
Oh !

i'm using asterix_cat048_1_14.xml
 i tried with asterix_cat048_1_21, but i didnt recompiled since this

**Comment by kentpachi** [comment]
have to remember how to recompile i'll give a try

**Comment by dsalantic** [comment]
You can use asterix_cat048_1_14.xml as well, just copy the SP definition part.
You need to take the latest version of source code and compile it (just type make in src directory).

**Comment by kentpachi** [comment]
Ok that works great i have just like you 

"CAT":16,
		"PROB":0},{
		"CAT":32,
		"PROB":0},{
		"CAT":48,
		"PROB":50},{
		"CAT":64,
		"PROB":50}]

but CAT value should be between 0x00 and 0x50  so i set encode="hex" in xml and it works just like a charm

thank you very much for your help and great job

**Comment by dsalantic** [comment]
I'm glad it works fine now.
bye
