### ISSUE TITLE
Is the asterix capable to project the cat 240 stream into visulized image?

### ISSUE THREAD

**Issue by julianraheema** [CroatiaControlLtd/asterix#65]
It is not an issue, but a clarification question. I do have a stream of radar data cat 240 coming from SPX Radar Simulator and asterix is successfully receiving the stream and parsing it. What I need is to visualizing radar data on my monitor as radar image. See the attachment.

 I am trying to write a code in python to parse the cat 240 line by line output generated by asterix then use the "Data Item I240/050, Video Block Low Data Volume" data to construct my radar image, but no luck so far. I am open to any suggestions!

For three seconds, I get 6000 Data Block output from Asterix, and here is a sample output of Data Block from "asterix -i ip:ip:port" command for one record is: 

"-------------------------
Data Block 1
Category: 240
Len: 1376
-------------------------
Data Record 1
Len: 1376
CRC: 3555AA95
Timestamp: 66896282

Item 010 : Data Source Identifier
[ 00 00 ]
	System Area Code: 0
	System Identification Code: 0

Item 000 : Message Type
[ 02 ]
	Message Type: 2 (Video message)

Item 020 : Video Record Header
[ 0B E8 C3 56 ]
	Message Sequence Identifier: 199803734

Item 041 : Video Header Femto
[ 2A 9A 2A B3 00 00 00 00 02 54 75 86 ]
	Start azimuth of the cells group: 10906 (59.9084473 deg)
	End azimuth of the cells group: 10931 (60.0457764 deg)
	Starting range of the cells group, expressed in number of cells: 0
	Video cell duration in femto-seconds: 39089542

Item 048 : Video Cells Resolution and Data Compression Indicator
[ 00 04 ]
	Data Compression Indicator: 0 (No compression applied)
	spares bit set to 0: 0
	Bit resolution used for the coding of the amplitude of the video signal in every cell of a video group: 4 (High Resolution (coding length = 8 bits))

Item 049 : Video Octets and Video Cells Counters
[ 05 14 00 05 14 ]
	Number of valid octets: 1300
	Number of valid cells: 1300

Item 051 : Video Block Medium Data Volume
[ 15 05 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 2E 23 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 21 21 21 21 21 21 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 25 25 25 25 25 25 25 25 25 24 24 24 23 23 23 23 23 22 22 22 22 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 23 23 23 23 23 23 22 22 22 22 22 22 22 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 22 22 22 22 22 22 22 22 21 21 21 23 23 23 23 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 24 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]
	Video signal amplitude of the cells in the group: 052E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E23262626262626262626262626262626262626262626262626
	Video signal amplitude of the cells in the group: 2626262626262626262626262626262625252525252525252525252525252525252525212121212121FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
	Video signal amplitude of the cells in the group: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
	Video signal amplitude of the cells in the group: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
	Video signal amplitude of the cells in the group: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF252525252525252524242424242424242424242424242424242424252525252525252525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252525252525252323232323232323232323232323232323232323232323232323232323232326262626262626262626262626262626
	Video signal amplitude of the cells in the group: 26262626262626262626262626262626262626262626262626262626262626262626252525252525252525242424232323232322222222242424242424242424
	Video signal amplitude of the cells in the group: 24242424242424242424242424242424242424242424242424242424242323232323232323232323232323222222222222222525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252525252525252525252525252524242424242424242424242424242424242424242424242424242424242424242424242424242424
	Video signal amplitude of the cells in the group: 24242424242424242424242525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252524242424242422222222222222222121212323232324242424242424242424242425252525252525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252525252525252525252525262626262626262626262626262626262626262626262626262626262626262626262626262624252525
	Video signal amplitude of the cells in the group: 25252525252525252525252525252525252525252525252525252525252525252525252626262626262626262626262626262626262626262626262626262626
	Video signal amplitude of the cells in the group: 26262626262626262626262626262626262626262626262626262626262626262626262626262626262624262626262626262626262626262626262626262626
	Video signal amplitude of the cells in the group: 26262626262626262626262626262626262525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252525252525252525252525252525252626262626262626262626262626262626262626262626262626262626262626262626262626
	Video signal amplitude of the cells in the group: 24242424242424242424252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252526262626262626262626262626262626262626262626262626262626262626262626262626262525252525252525252525252525
	Video signal amplitude of the cells in the group: 25252525252525252525252525252424242424242424242424242424242424242525252525252525252525252525252525252626262626262626262626262626
	Video signal amplitude of the cells in the group: 26262626262626262626262626262626262626262626262624242424242424242424242424242424242424242424242424262626262626262626262626262626
	Video signal amplitude of the cells in the group: 26262626262626262626262626262626262626260000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Item 140 : Time Of Day
[ 82 A8 2E ]
	Time Of Day: 8562734 (66896.3593750 s)

-------------------------
Data Block 2
Category: 240
Len: 780
-------------------------
Data Record 1
Len: 780
CRC: 61E68A4A
Timestamp: 66896282

Item 010 : Data Source Identifier
[ 00 00 ]
	System Area Code: 0
	System Identification Code: 0

Item 000 : Message Type
[ 02 ]
	Message Type: 2 (Video message)

Item 020 : Video Record Header
[ 0B E8 C3 57 ]
	Message Sequence Identifier: 199803735

Item 041 : Video Header Femto
[ 2A 9A 2A B3 00 00 05 14 02 54 75 86 ]
	Start azimuth of the cells group: 10906 (59.9084473 deg)
	End azimuth of the cells group: 10931 (60.0457764 deg)
	Starting range of the cells group, expressed in number of cells: 1300
	Video cell duration in femto-seconds: 39089542

Item 048 : Video Cells Resolution and Data Compression Indicator
[ 00 04 ]
	Data Compression Indicator: 0 (No compression applied)
	spares bit set to 0: 0
	Bit resolution used for the coding of the amplitude of the video signal in every cell of a video group: 4 (High Resolution (coding length = 8 bits))

Item 049 : Video Octets and Video Cells Counters
[ 02 EC 00 02 EC ]
	Number of valid octets: 748
	Number of valid cells: 748

Item 050 : Video Block Low Data Volume
[ BB 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 22 22 22 22 22 22 22 22 23 23 23 23 23 23 23 23 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 23 23 23 23 23 23 23 23 23 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 22 22 22 22 22 22 22 22 22 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 ]
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 23232323
	Video signal amplitude of the cells in the group: 23232323
	Video signal amplitude of the cells in the group: 23232323
	Video signal amplitude of the cells in the group: 23232323
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252524
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242422
	Video signal amplitude of the cells in the group: 22222222
	Video signal amplitude of the cells in the group: 22222223
	Video signal amplitude of the cells in the group: 23232323
	Video signal amplitude of the cells in the group: 23232326
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26232323
	Video signal amplitude of the cells in the group: 23232323
	Video signal amplitude of the cells in the group: 23232525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262622
	Video signal amplitude of the cells in the group: 22222222
	Video signal amplitude of the cells in the group: 22222222
	Video signal amplitude of the cells in the group: 24252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252526
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 25252525
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 24242424
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626
	Video signal amplitude of the cells in the group: 26262626

Item 140 : Time Of Day
[ 82 A8 2E ]
	Time Of Day: 8562734 (66896.3593750 s)
"

![selection_009](https://user-images.githubusercontent.com/6541950/27653482-06397f44-5bf4-11e7-8a45-a23b4ec52cf0.png)

**Comment by dsalantic** [comment]
Asterix parser is used only to decode the asterix binary format to text or json.
There is no posibility to produce the radar video image. You will have to do it yourself using the decoded information. I never used category 240, so I can't help you more.
