### ISSUE TITLE
Python Modul

### ISSUE THREAD

**Issue by julianraheema** [CroatiaControlLtd/asterix#66]
Error:  parsed = asterix.parse(asterix_packet,'text')

TypeError: parse() takes exactly 1 argument (2 given)

and the documentation on the _init_.py says this:
# If you want to receive textual presentation of asterix packet instead of list use 'text' parameter::
    formatted = asterix.parse(asterix_packet, 'text')
    print(formatted)

also how can I subscribe and parse the real time data coming from ip and port ?

**Comment by dsalantic** [comment]
Sorry, I forgot to update the help and examples. Now it is done.
To see textual presentation use:
```
parsed = asterix.parse(asterix_packet)
print(asterix.describe(parsed))
```

To subscribe to multicast stream use following code (from examples):

```
import socket
import struct
import asterix

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(('', 21111))
mreq = struct.pack("=4sl", socket.inet_aton("232.1.1.11"), socket.INADDR_ANY)
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)

counter=1

while True:
    asterix_packet = sock.recv(10240)
    parsed = asterix.parse(asterix_packet)
    print('%d. Receiver received = %s' % (counter, parsed))
    counter += 1
```

**Comment by julianraheema** [comment]
Thank you.
