### ISSUE TITLE
how to install under windows?

### ISSUE THREAD

**Issue by bianbian-org** [CroatiaControlLtd/asterix#68]
>pip install asterix-decoder

...
    python_parser.cpp
    ./src/asterix\XMLParser.h(27): fatal error C1083: Cannot open include file:: “expat.
h”: No such file or directory
    error: command 'C:\\Dev\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' fail
ed with exit status 2

I then downloaded and installed libexpat, the error remains.

thanks.

**Comment by dsalantic** [comment]
Unfortunatelly, Windows building is not supproted yet. Only Linux or iOS.

**Comment by robertonav20** [comment]
I want install the library in windows OS.
it's available?

Thanks.

**Comment by dsalantic** [comment]
It is possible, but you have to install cygwin first and then use cygwin tools (make, gcc) together with libexpat-dev library.

**Comment by robertonav20** [comment]
I've installed cygwin but i dont understand your advice "use cygwin tools (make, gcc) together with libexpat-dev library."

**Comment by dsalantic** [comment]
When you install Cygwin, use Cygwin terminal.
Enter the asterix/src folder and execute: 
make install

asterix.exe shall be created in install folder
If you get error "expat.h: No such file or directory", it means that you do not have expat-dev package installed. Use your Cygwin installation tool to install that package and then make again.

**Comment by robertonav20** [comment]
Great!! it's worked for me!

**Comment by robertonav20** [comment]
I've used asterix.exe into install folder

**Comment by ifsnop** [comment]
> When you install Cygwin, use Cygwin terminal.
> Enter the asterix/src folder and execute:
> make install
>
> asterix.exe shall be created in install folder
> If you get error "expat.h: No such file or directory", it means that you
> do not have expat-dev package installed. Use your Cygwin installation tool
> to install that package and then make again.
>

Last time I tried and I wasn't able to compile under Windows, so I ended up
modified makefiles to cross compile from Linux to Windows.

Do you think this could be useful?

>

**Comment by robertonav20** [comment]
Yes, of course.
