### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by tojoaijo** [CroatiaControlLtd/asterix#70]
Hi everyone
I'm using Asterix on linux Debian, I have done the installation but I don't know how to run it
would anyone help me?
thanks

**Comment by dsalantic** [comment]
Hi,

If you are using asterix application, see examples here: https://github.com/CroatiaControlLtd/asterix/tree/master/install

If you are useing asterix parser through python see here:
https://github.com/CroatiaControlLtd/asterix/tree/master/asterix/examples

**Comment by tojoaijo** [comment]
Hi,
Thank you :)
Does that application can read this file extension "**.ff**" ?

**Comment by dsalantic** [comment]
If that file is in so called "final format" than yes.
You need to call with -F option like this:
asterix.exe -F  -f your_file.ff

**Comment by tojoaijo** [comment]
sorry but where is that file "asterix.exe"? I can't find it

**Comment by tojoaijo** [comment]
![capture d ecran_2018-03-14_14-26-50](https://user-images.githubusercontent.com/5299914/37400316-9be01b80-2795-11e8-9097-c88785e8d070.png)

**Comment by tojoaijo** [comment]
sorry, I know how to launch the app now.
Thank you for your help :)

**Comment by dsalantic** [comment]
Do the following to install asterix:

cd /home/tojo/Documents/asterix/src
make
make install
cd /home/tojo/Documents/asterix/install
./asterix

**Comment by tojoaijo** [comment]
thank you for your help @dsalantic :)
Just one last question, can we specify an output format to txt? and if it's possible, where is the destination or how to specify it?

**Comment by dsalantic** [comment]
Output is always textual, and you can specifiy following textual output formats with on of following flags:

-l  Output will be printed as one line per item. This format is suitable for parsing.
-x  Output will be printed in XML format.
-j    Output will be printed in compact JSON format (one object per line).
-jh   Output will be printed in human readable JSON format (one item per line).

Output is always printed on standard console, so  you can just redirect it to file:
`asterix -F -f inputfile.ff  > output.file`
