### ISSUE TITLE
Problem while decoding asterix data cat 021

### ISSUE THREAD

**Issue by tojoaijo** [CroatiaControlLtd/asterix#71]
Hi here
I want to decode asterix data cat 021 files and I got the following errors:

> DEBUG:   Mar 15 15:58:13 2018 (InputParser.cpp) [15 00 2B FF A1 DA B9 E0 00 28 A8 BF 93 F9 50 0D 20 91 14 40 07 EE 17 30 00 07 08 05 78 00 00 08 B7 5D 88 08 15 F2 C3 6E 60 00 00]
ERROR:   Mar 15 15:58:13 2018 (asterixformat.cxx) DataItem::parse needed length=2 , and there is only 0 : [  ]
ERROR:   Mar 15 15:58:13 2018 (asterixformat.cxx) Wrong length in DataItem format for CAT021/I145
ERROR:   Mar 15 15:58:13 2018 (asterixformat.cxx) Data Record bytes: [ FF A1 DA B9 E0 00 28 A8 BF 93 F9 50 0D 20 91 14 40 07 EE 17 30 00 07 08 05 78 00 00 08 B7 5D 88 08 15 F2 C3 6E 60 00 00 ]
ERROR:   Mar 15 15:58:13 2018 (asterixformat.cxx) Record not parsed properly. CAT021 len=40

Can anyone help me to identify the issue? is the problem from the files or from the application?

**Comment by dsalantic** [comment]
In what format is you input file ?
What arguments you used when calling application ?

**Comment by tojoaijo** [comment]
Hi @dsalantic 
The input file is in ".ff"
And I used the commande 
``
`` ./asterix`` -F -f myfile.ff > data1.txt

**Comment by dsalantic** [comment]
I looks like regular CAT021 record, but there is some error in parsing.
Do you mabye know which version of CAT021 format is in there ?
Currently you are parsing with v1.8, but if it is old format (e.g. 0.26) it is not compatible.
You can try the following to try parsing with CAT012 v.26 :  

In file  install/config/asterix.ini

replace line :
asterix_cat021_1_8.xml

with:
asterix_cat021_0_26.xml

**Comment by tojoaijo** [comment]
thank you @dsalantic for your help, I tried with the "asterix_cat021_0_23.xml" and there is no more error

**Comment by dsalantic** [comment]
Great. Let me know if you find any problems.
