### ISSUE TITLE
wrong repetitive fixed length on I048/120

### ISSUE THREAD

**Issue by quisenbeje** [CroatiaControlLtd/asterix#72]
in the file asterix_cat048_1_21.xml, i would expect the fixed length of the repetitive section to be defined as 6, rather than 7, (bits 1-48) - similar to the way I034/070 is defined with length 2 (bits 1-16). am i misunderstanding the format?

**Comment by dsalantic** [comment]
Yes, you are right. Thank you.
It's fixed now.
