### ISSUE TITLE
error on Win installation of package

### ISSUE THREAD

**Issue by nadrealista** [CroatiaControlLtd/asterix#73]
Pozdrav iz USA, 

Pokusavam da instaliram vas program ali imam problema sa greskama koje kazu slijedece (ispod), Kakave su sanse da to neko pogleda i uputi me kako da uspjesno zavrsim insataliranje.

Pozdrav,
Dejan

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Python27\Lib\asterix_decoder-0.5.0>C:\Python27\python.exe setup.py install
running install
running bdist_egg
running egg_info
writing asterix_decoder.egg-info\PKG-INFO
writing top-level names to asterix_decoder.egg-info\top_level.txt
writing dependency_links to asterix_decoder.egg-info\dependency_links.txt
reading manifest file 'asterix_decoder.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'asterix_decoder.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib.win32-2.7
creating build\lib.win32-2.7\asterix
copying asterix\version.py -> build\lib.win32-2.7\asterix
copying asterix\__init__.py -> build\lib.win32-2.7\asterix
creating build\lib.win32-2.7\asterix\config
copying asterix\config\asterix.dtd -> build\lib.win32-2.7\asterix\config
copying asterix\config\asterix_bds.xml -> build\lib.win32-2.7\asterix\config
copying asterix\config\asterix_cat001_1_1.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat002_1_0.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat004_1_8.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat008_1_0.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat010_1_1.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat019_1_2.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat020_1_7.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat021_1_8.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat023_1_2.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat030_6_2.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat031_6_2.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat032_7_0.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat034_1_27.xml -> build\lib.win32-2.7\asterix\co
nfig
copying asterix\config\asterix_cat048_1_21.xml -> build\lib.win32-2.7\asterix\co
nfig
copying asterix\config\asterix_cat062_1_16.xml -> build\lib.win32-2.7\asterix\co
nfig
copying asterix\config\asterix_cat063_1_3.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat065_1_3.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat240_1_3.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat247_1_2.xml -> build\lib.win32-2.7\asterix\con
fig
copying asterix\config\asterix_cat252_7_0.xml -> build\lib.win32-2.7\asterix\con
fig
creating build\lib.win32-2.7\asterix\examples
copying asterix\examples\__init__.py -> build\lib.win32-2.7\asterix\examples
copying asterix\examples\multicast_receive.py -> build\lib.win32-2.7\asterix\exa
mples
copying asterix\examples\multicast_send_receive.py -> build\lib.win32-2.7\asteri
x\examples
copying asterix\examples\read_pcap_file.py -> build\lib.win32-2.7\asterix\exampl
es
copying asterix\examples\read_raw_bytes.py -> build\lib.win32-2.7\asterix\exampl
es
copying asterix\examples\read_raw_file.py -> build\lib.win32-2.7\asterix\example
s
creating build\lib.win32-2.7\asterix\sample_data
copying asterix\sample_data\cat034.raw -> build\lib.win32-2.7\asterix\sample_dat
a
copying asterix\sample_data\cat048.raw -> build\lib.win32-2.7\asterix\sample_dat
a
copying asterix\sample_data\cat062cat065.raw -> build\lib.win32-2.7\asterix\samp
le_data
copying asterix\sample_data\cat_034_048.pcap -> build\lib.win32-2.7\asterix\samp
le_data
copying asterix\sample_data\cat_062_065.pcap -> build\lib.win32-2.7\asterix\samp
le_data
creating build\lib.win32-2.7\asterix\test
copying asterix\test\__init__.py -> build\lib.win32-2.7\asterix\test
copying asterix\test\parsing_error_1.xml -> build\lib.win32-2.7\asterix\test
copying asterix\test\parsing_error_2.xml -> build\lib.win32-2.7\asterix\test
copying asterix\test\test_init.py -> build\lib.win32-2.7\asterix\test
copying asterix\test\test_parse.py -> build\lib.win32-2.7\asterix\test
copying asterix\test\valgrind-python.supp.txt -> build\lib.win32-2.7\asterix\tes
t
running build_ext
building '_asterix' extension
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\src
creating build\temp.win32-2.7\Release\src\python
creating build\temp.win32-2.7\Release\src\asterix
C:\Users\554083\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.
0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./asterix/python -I./src/
asterix -I./src/engine -IC:\Python27\include -IC:\Python27\PC /Tc./src/python/as
terix.c /Fobuild\temp.win32-2.7\Release\./src/python/asterix.obj -DPYTHON_WRAPPE
R
asterix.c
C:\Users\554083\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.
0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./asterix/python -I./src/
asterix -I./src/engine -IC:\Python27\include -IC:\Python27\PC /Tc./src/python/py
thon_wrapper.c /Fobuild\temp.win32-2.7\Release\./src/python/python_wrapper.obj -
DPYTHON_WRAPPER
python_wrapper.c
./src/python/python_wrapper.c(44) : error C2275: 'PyObject' : illegal use of thi
s type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
./src/python/python_wrapper.c(44) : error C2065: 'arglist' : undeclared identifi
er
./src/python/python_wrapper.c(45) : error C2275: 'PyObject' : illegal use of thi
s type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
./src/python/python_wrapper.c(45) : error C2065: 'result' : undeclared identifie
r
./src/python/python_wrapper.c(46) : error C2065: 'arglist' : undeclared identifi
er
./src/python/python_wrapper.c(46) : warning C4047: '=' : 'int' differs in levels
 of indirection from 'PyObject *'
./src/python/python_wrapper.c(47) : error C2065: 'result' : undeclared identifie
r
./src/python/python_wrapper.c(47) : error C2065: 'arglist' : undeclared identifi
er
./src/python/python_wrapper.c(47) : warning C4047: 'function' : 'PyObject *' dif
fers in levels of indirection from 'int'
./src/python/python_wrapper.c(47) : warning C4024: 'PyObject_CallObject' : diffe
rent types for formal and actual parameter 2
./src/python/python_wrapper.c(47) : warning C4047: '=' : 'int' differs in levels
 of indirection from 'PyObject *'
./src/python/python_wrapper.c(48) : error C2065: 'arglist' : undeclared identifi
er
./src/python/python_wrapper.c(48) : error C2065: 'arglist' : undeclared identifi
er
./src/python/python_wrapper.c(48) : error C2065: 'arglist' : undeclared identifi
er
./src/python/python_wrapper.c(49) : error C2065: 'result' : undeclared identifie
r
./src/python/python_wrapper.c(49) : warning C4047: '==' : 'int' differs in level
s of indirection from 'void *'
./src/python/python_wrapper.c(52) : error C2065: 'result' : undeclared identifie
r
./src/python/python_wrapper.c(52) : error C2065: 'result' : undeclared identifie
r
./src/python/python_wrapper.c(52) : error C2065: 'result' : undeclared identifie
r
./src/python/python_wrapper.c(64) : error C2143: syntax error : missing ';' befo
re 'type'
./src/python/python_wrapper.c(65) : error C2065: 'ret' : undeclared identifier
./src/python/python_wrapper.c(74) : error C2143: syntax error : missing '{' befo
re '*'
./src/python/python_wrapper.c(104) : warning C4133: 'return' : incompatible type
s - from 'PyObject *' to 'int *'
./src/python/python_wrapper.c(132) : error C2275: 'PyObject' : illegal use of th
is type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
./src/python/python_wrapper.c(132) : error C2065: 'lstBlocks' : undeclared ident
ifier
./src/python/python_wrapper.c(135) : error C2065: 'lstBlocks' : undeclared ident
ifier
./src/python/python_wrapper.c(135) : warning C4047: '==' : 'int' differs in leve
ls of indirection from 'void *'
./src/python/python_wrapper.c(137) : error C2065: 'lstBlocks' : undeclared ident
ifier
./src/python/python_wrapper.c(137) : warning C4047: 'return' : 'PyObject *' diff
ers in levels of indirection from 'int'
./src/python/python_wrapper.c(162) : error C2275: 'PyObject' : illegal use of th
is type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
./src/python/python_wrapper.c(162) : error C2065: 'py_output' : undeclared ident
ifier
./src/python/python_wrapper.c(165) : error C2065: 'py_output' : undeclared ident
ifier
./src/python/python_wrapper.c(165) : warning C4047: '==' : 'int' differs in leve
ls of indirection from 'void *'
./src/python/python_wrapper.c(171) : error C2065: 'py_output' : undeclared ident
ifier
./src/python/python_wrapper.c(171) : warning C4047: 'return' : 'PyObject *' diff
ers in levels of indirection from 'int'
error: command 'C:\\Users\\554083\\AppData\\Local\\Programs\\Common\\Microsoft\\
Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

C:\Python27\Lib\asterix_decoder-0.5.0>cd C:\Python27\Lib\asterix_decoder-0.5.0

**Comment by dsalantic** [comment]
I'm sorry, but python Windows installation is not supported.
Only Linux or Mac iOS.
