### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tojoaijo** [CroatiaControlLtd/asterix#74]
Hi all,
It's not an issue but I want help if you can.
I need a tool or a application to display the data we have decoded on map, like google MAP.
Thanks

**Comment by tojoaijo** [comment]
We extracted data from ADS-B (CAT021).
Do we need to extract manually the longitude, latitude and altitude or there have an app who can convert xml to kml?
Thank you @dsalantic

**Comment by railsGod** [comment]
Hi @tojoaijo, do you still need this tool? Display on Google Maps?

**Comment by tojoaijo** [comment]
Hi @railsGod,
Yes, I need it if you can help me :)
Thanks in advance

**Comment by railsGod** [comment]
@tojoaijo please contact me at railsGod@protonmail.com

**Comment by tojoaijo** [comment]
thanks
