### ISSUE TITLE
Path with spaces problems

### ISSUE THREAD

**Issue by Sacredelf** [CroatiaControlLtd/asterix#77]
Hello, I tried to charge a file that's inside a folder that has name with spaces, and it does not run.

./asterix.exe -P -f ../../../Desktop/Hola\ Hola/prueba.pcap

results:
ERROR:   Jul 10 11:01:01 2018 (channelfactory.cxx) Unknown format 'Hola/prueba.pcap:0:1'.

I tried every kind of combinations, but nothing to do.
Could you help me please?
Thank you in advance

**Comment by dsalantic** [comment]
Unfortunatelly it is not supported in current version. You need to have path without spaces.
Anyway, I'll keep it in my todo list and fix it when I find time.

**Comment by Sacredelf** [comment]
Thank you for your reply, very kind.
Could be possible that the program has the same problem when I chose a file from a different source? I mean when the file has stored in a usb or another partition of the hard disk, like D:/

**Comment by dsalantic** [comment]
This is fixed now in version 2.4.3 (python_v0.5.5)
