### ISSUE TITLE
How to read datas in cast?

### ISSUE THREAD

**Issue by Sacredelf** [CroatiaControlLtd/asterix#79]
Hi, thanks you for helping me with the previous problem.

I'd like to ask you how can use de decoder reading datas sent by a sensor. I mean, how to read the datas like wireshark in streaming,  because the  -i m:i:p[:s] use a multicast. To do this, have I to mount a multicast? and what is exactly the interface address? 'cause I understand that:  Multicast IP address(address multicast between 224.0.0.0 a 239.255.255.255):Interface address(the gateway??):Port(source port)[:Source address], is it right?

**Comment by dsalantic** [comment]
To receive multicast data from sensor start the application with -i option like this:

asterix -i 232.1.1.11:192.168.0.1:22222

where 
232.1.1.11  is the muticast address
22222 is the multicast port
192.168.0.1 is the address of local interface on which you are listening (note that you can have multiple local interfaces on server, so it is necessary to specify which one to use)
