### ISSUE TITLE
issue with cat240 Non-Standard Data Fields

### ISSUE THREAD

**Issue by punx77** [CroatiaControlLtd/asterix#87]
Hello,
I'm trying to use your library with asterix radar stream, but with a cat240 stream, which implement Non-Standard Data Fields (section 4.2.5 of document 20120401-asterix-spec-v2.0.pdf ) seems to fail to decode the stream, while using it with standard cat240 radar stream I'm using it with success. It is possible to solve this issue?

**Comment by dsalantic** [comment]
Please pull the latest version now. I added SP and RE fields to CAT240.
Note that it should now parse the data correctly, but it will just show SP and RE values byte by byte, because those fields are not defined in specification.
If you want to show them correctly you have to modify XML files for CAT240 yourself.

**Comment by punx77** [comment]
Hello, 
thank you very much. I'm trying to decode the stream with the new xlm for cat240 you modified, but seems something still have problem, because I'm not able to decode correctly fields. Not the SP filed, but also other fields still have problems. I attach the wireshark datastream. Could you please verify
thank you

[radar-capture-livorno-bandak-newprotocol-multicIPMAC.zip](https://github.com/CroatiaControlLtd/asterix/files/3021738/radar-capture-livorno-bandak-newprotocol-multicIPMAC.zip)

**Comment by punx77** [comment]
sorry, we solved the issue thanx to your xml file (I made a mistake, this is the reason for my last post). We have to fix something but it is related to the payload of SP field. Thank you. best regards
