### ISSUE TITLE
Sometimes m_nTimestamp can be zero

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#88]
https://github.com/CroatiaControlLtd/asterix/blob/4fa31bd6eb72b1e98069507b0304ea750ed87ed8/src/asterix/DataRecord.cpp#L207

Could we get rid of this "if (m_nTimestamp != 0)" comparison? Sometimes (when crossing midnight) this could be zero, and because of the if, timestamp won't be printed.

There are 3 of them.

**Comment by dsalantic** [comment]
Done
