### ISSUE TITLE
Compiling fails under Alphine docker os image

### ISSUE THREAD

**Issue by mictibo** [CroatiaControlLtd/asterix#90]
udpdevice.hxx:63:5: error: 'fd_set' does not name a type; did you mean 'tzset'?
This can get solved by adding the <sys/select.h> library in the devicefactory.hxx and by 
Installing in the Docker image expat: "apk add expat-dev"

**Comment by dsalantic** [comment]
I added missing include.
Yes, asterix depends on expat-dev, so please include it to your docker image.
