### ISSUE TITLE
Suggestion to plot tracks?

### ISSUE THREAD

**Issue by nunojpg** [CroatiaControlLtd/asterix#94]
Hi,

I see in the source code there is a KML output option, but it throws a error (channelfactory.cxx) Unknown format 'ASTERIX_KML'.

Maybe you are aware of another way to plot Cat 21 tracks?

Thanks!

**Comment by alepinio** [comment]
So you actually dumped a set of ASTERIX data blocks and you want to plot them offline?

Or you want to do it in real time like an ATCC?

**Comment by nunojpg** [comment]
I was looking for a real time input of asterix. Basic features and no reliability required, just for demos. I could only find ASTERIX Toolkit.

**Comment by alepinio** [comment]
I see. I'm sorry I can't help you, I do not know any OSS to plot ASTERIX like an ATCC.
