### ISSUE TITLE
Bad definition in DataItem 010/250

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#95]
In file asterix_cat010_1_1.xml, the definition for dataitem 250 contains a from/to pair that is invalid: 

~~~
 <DataItem id="250" rule="mandatory">
        <DataItemName>Mode S MB Data</DataItemName>
        <DataItemDefinition>Mode S Comm B data as extracted from the aircraft transponder.</DataItemDefinition>
        <DataItemFormat desc="Repetitive Data Item starting with a one-octet Field Repetition Indicator (REP) followed by at least one BDS message comprising one seven octet BDS
            <Repetitive>
                <Fixed length="8">
                    <Bits from="64" to="9">
~~~

Such value will trigger an error: ERROR:   Oct  9 14:26:33 2019 (asterixformat.cxx) DataItemBits::getUnsigned : Wrong parameter.m Number of bits = 56, and must be between 1 and 32.

The same definition was included in asterix_cat048_1_21.xml, but was latter changed to:

~~~
<DataItem id="250" >
        <DataItemName>Mode S Comm B data</DataItemName>
        <DataItemDefinition>Mode S Comm B data extracted from the aircraft transponder</DataItemDefinition>
        <DataItemFormat desc="Repetitive 8 byte BDS registers">
        <Repetitive>
            <BDS/>
        </Repetitive>
        </DataItemFormat>
        <DataItemNote/>
    </DataItem>
~~~

when bds decoding was implemented back in 2016.

You could test it with the following asterix block:

~~~
0A 00 4D FF FF B1 B0 00 69 01 29 03 00 23 E9 00 1F 06 2B 4D FB A9 47 DB 23 0E E5 9D EA F5 1B D2 03 88 0B 11 00 6E 01 8A 05 E6 03 01 00 03 2D 4C A3 4D 00 58 F1 73 48 88 20 01 10 01 00 80 FD 00 00 10 00 87 01 D4 0D 1E 00 17 00 00 00
~~~

What do you recommend, change the 010/250 definition to match the one in 048/250 or fix the code in DataItemBits.cpp: unsigned long DataItemBits::getUnsigned?

**Comment by dsalantic** [comment]
You are right.
Now I changed this and all other categories that have BDS register to the same format as in CAT048.
I need to do some more tests and then I'll include it in new version.
