### ISSUE TITLE
Config xml for CAT011

### ISSUE THREAD

**Issue by niklasathouseoftest** [CroatiaControlLtd/asterix#96]
Hi,
I was trying to decode some CAT011 data, using the Python package, but the result didn't make much sense to me. Then I discovered that there was no config file for that category which would explain why. 
So, therefore I wonder if you have any plans to add support for CAT011?

Thanks!
/Niklas

**Comment by dsalantic** [comment]
Hi,
I don't have plans for CAT011 for now.
If you are willing to prepare and test the XML config file I'm ready to include it to distribution.
You can use some of the existing XML files and modify it to include CAT11 specification.

BR,
Damir

**Comment by niklasathouseoftest** [comment]
Thanks a lot for your reply, Damir! I will take a look at creating such an xml and I can absolutely share it. Only problem is that the project I'm on, is not utilizing all the data items in cat11 and therefore it'll be a bit hard to know whether I get all the xml right, or not. But I'll create a pull request once I have something that works in my end. :)

**Comment by dsalantic** [comment]
I fixed your definition of I380. Please try it.
It is now on git, but not yet on pip. Will be after few more tests.

**Comment by niklasathouseoftest** [comment]
I will absolutely try it out. Really appreciate your help on this. Thanks!
