### ISSUE TITLE
New category file not picked up?

### ISSUE THREAD

**Issue by niklasathouseoftest** [CroatiaControlLtd/asterix#97]
I have created a definition xml file for category 11 now, however I doesn't seem to be picked up properly when trying to decode.

My record(s) looks like this after attempting to decode:
Asterix record: 1 
Len: 18
CRC: 736E6172
Timestamp: 1571142086779 (2019-10-15 14:21:26.779000)
Category: 11 (Transmission of A-SMGCS Data)
Item: crc ()736E6172
Item: ts ()1571142086779
Item: len ()18

The code I'm running is basically the same as the example "read_raw_bytes.py" with different data and two extra lines for defining the config file. 
Please see the attached zip for definition xml and code example.
[AsterixExample.zip](https://github.com/CroatiaControlLtd/asterix/files/3729229/AsterixExample.zip)

Thanks!
Niklas

**Comment by dsalantic** [comment]
You forgot to define UAP in your XML.
Now I corrected it and pushed it to repository.
Thank you for your contribution.

**Comment by niklasathouseoftest** [comment]
Super! Thanks a lot!  👍
