### ISSUE TITLE
ADSB latitude out of range

### ISSUE THREAD

**Issue by SimKuanGOH** [CroatiaControlLtd/asterix#98]
Hi developer, I used the decoder to read ADSB asterix and got latitude information that is out of range. Below is an example of the asterix.parse()

'I131_Lat_desc': 'Latitude In WGS.84 in twos complement. Range -90 <= Lat <= 90 deg.', 'I131_Lat_val': -104.12836851552129

**Comment by dsalantic** [comment]
Yes, the protocol definition allows this field to contain value from -360 to 360.
But the meaningful values are -90 to 90.
Do you see it regularly or just once ?
If this is only one occurrence, then my guess is that the signal was not read correctly and you can ignore it.
