### ISSUE TITLE
problem decoding I048/100 Mode-C Code and Code Confidence Indicator

### ISSUE THREAD

**Issue by alepinio** [CroatiaControlLtd/asterix#99]
Hi,

When I send the chunk
```
V G 0 0  C1  A1  C2  A2  C4  A4  B1  D1  B2  D2  B4  D4
0 0 0 0   0   0   1   0   0   0   0   0   0   0   0   0

0 0 0 0 QC1 QA1 QC2 QA2 QC4 QA4 QB1 QD1 QB2 QD2 QB4 QD4
0 0 0 0   0   0   0   0   0   0   0   0   0   0   0   1
```
as Data Item I048/100 Mode-C Code and Code Confidence Indicator and use this module for decoding it I'm getting
```
'I100': {'QC1': {'val': 0}, 'QA2': {'val': 0}, 'G': {'val': 0}, 'ModeC': {'val': 1}, 'QB1': {'val': 0}, 'QB2': {'val': 0}, 'QA1': {'val': 0}, 'V': {'val': 1}, 'QC4': {'val': 0}, 'QD2': {'val': 0}, 'QD1': {'val': 1}, 'QA4': {'val': 0}, 'QC2': {'val': 0}, 'spare': {'val': 0}}
```
as result.

Supposing I correctly understood the implementation, decoding of mode C code isn't implemented and there is a copy&paste mistake in the least significant pulse quality bits (`asterix/asterix/config/asterix_cat048_1_21.xml`).

Is that possible?

Thank you very much, Alejandro

PS: great repo!

---

**edited 7/11**: see https://github.com/CroatiaControlLtd/asterix/issues/99#issuecomment-551059409

**Comment by dsalantic** [comment]
You are right. There was a typo in last 2 bits of I100. Now I corrected it.
For mode C decoding, it is not decoded. If you know how to decode it to gray notation let me know and I could implement it.

**Comment by alepinio** [comment]
Thank you very much for the new release with the correction!

So, about mode C decoding, just to confirm, I understand that as you are currently outputting codes 1, 2 and A in octal representation, by analogy you don't want to output code C bit by bit (as it is done with the confidences for example) but rather the corresponding flight level in decimal representation.

Is that correct?

**Comment by ifsnop** [comment]
For an implementation of a grey to binary decoder, with some test cases, see:

http://www.ccsinfo.com/forum/viewtopic.php?p=140960#140960

**Comment by alepinio** [comment]
Just in case, do not look for an implementation of a mode C decoder in the source code of wireshark.

I'm currently using wireshark for quick and dirty ASTERIX Data Category 048 decoding and as you can see in [epan/dissectors/packet-asterix.c](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-asterix.c) and in the screenshot I'm attaching, the code is being outputted bitwise.

![Selection_020](https://user-images.githubusercontent.com/45610498/68330641-5d6fad00-00b2-11ea-9b05-4b286b162624.png)

**Comment by alepinio** [comment]
(wireshark decodes other data items though)

![Selection_021](https://user-images.githubusercontent.com/45610498/68330892-ca834280-00b2-11ea-9314-b2647bb0b73b.png)

**Comment by dsalantic** [comment]
OK, I see. You think it would be better to decode it bit by bit (like in Wireshark) then as integer (even if you can read the int and extract the bits from it by yourself).
Other way is to decode the gray notation directly (Diego thanks for the link).

It's not a problem to implement any of those, but I'm just afraid to break backward compatibility if somebody is using it in the way as it is now. Let me know your opinion.

**Comment by alepinio** [comment]
First of all, I've checked what I wrote in the message with which I started this issue. I've made a mistake. The dict with the decoded data does not correspond to the indicated bytes with respect to code C and the validation bit (all about pulse quality bits is correct though).

When using this module (version `0.5.9`) to decode
```
V G 0 0  C1  A1  C2  A2  C4  A4  B1  D1  B2  D2  B4  D4
0 0 0 0   0   0   1   0   0   0   0   0   0   0   0   0
```
for the first two octets of *Data Item I048/100 Mode-C Code and Code Confidence Indicator*, one gets
```
{'I100': {..., 'V': {'val': 0}, ..., 'ModeC': {'val': 512}, ...}
```
and not
```
{'I100': {..., 'V': {'val': 1}, ..., 'ModeC': {'val': 1}, ...}
```
as it is wrote. Sorry for the confusion.

**Comment by alepinio** [comment]
> OK, I see. You think it would be better to decode it bit by bit (like in Wireshark) then as integer (even if you can read the int and extract the bits from it by yourself).
> Other way is to decode the gray notation directly (Diego thanks for the link).
> 
> It's not a problem to implement any of those, but I'm just afraid to break backward compatibility if somebody is using it in the way as it is now. Let me know your opinion.

IMO it would be so useful if this module can provide
```
{'I100': {..., 'ModeC': {'val': FLIGHT_LEVEL}, ...}
```
rather than just the decimal representation of the binary number associated to the pulses present in the C code, with the decoding done according to [the table in the p. 118 of this document](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwjmjqDPktjlAhXfHLkGHfRuAnQQFjABegQIABAC&url=https%3A%2F%2Fwww.bazl.admin.ch%2Fdam%2Fbazl%2Fde%2Fdokumente%2FFachleute%2FRegulationen_und_Grundlagen%2Ficao-annex%2Ficao_annex_10_aeronauticaltelecommunicationsvolumeiv-surveillanc.pdf.download.pdf%2Ficao_annex_10_aeronauticaltelecommunicationsvolumeiv-surveillanc.pdf&usg=AOvVaw1vxOGl5Dv5gdjkwy4JjtWw).

Besides, this behavior is what would be expected by analogy with the current implementation of modes 1, 2 and A decoders. For example, when decoding an all-zero byte chunk for mode A one gets:
```
'I070': {'G': {'val': 0}, 'spare': {'val': 0}, 'V': {'val': 0}, 'Mode3A': {'val': '0000'}, 'L': {'val': 0}}
```
This is your project, but I personally do not like backwards compatibility as a religion. I think the improvement obtained justifies it.

**Comment by ifsnop** [comment]
As I see di100, it is useful to change the bits according to the quality,
so you could recover the correct mode c. But, this is also done in the
di090 (detected flight level), and hopefully, better that you can do it
(radar tracker may have more info to reconstruct mode c).

As this was designed for ssr (not for mode s), usefulness is under question
these days.

So for me, there is no point in translating bits to FL.

Kind regards,

**Comment by alepinio** [comment]
> As I see di100, it is useful to change the bits according to the quality, so you could recover the correct mode c. But, this is also done in the di090 (detected flight level), and hopefully, better that you can do it (radar tracker may have more info to reconstruct mode c). As this was designed for ssr (not for mode s), usefulness is under question these days. So for me, there is no point in translating bits to FL. Kind regards,

I don't understand what you say...in a SSR processing system, you build di090 only after having decoded the received code C. So, every SSR processing system already contains some kind of `code C ---> flight level` mapping.

If this module would implement mode C decoding, it could be used for testing SSR processing systems through the standard interface ASTERIX Data Category 048.

**Comment by ifsnop** [comment]
Right, every SSR processing system contains di090. And only when the processing system isn't capable of decoding correctly the pulses, it will generate di100, to be able to show which pulses were of high/low quality.

> If this module would implement mode C decoding, it could be used for testing SSR processing systems through the standard interface ASTERIX Data Category 048.
So, for doing this, you are going to operate with the bits in di100 (maybe changing low quality 0 bits o 1, for example, and then encode it to FL.

My point is, you don't need CroatiaControl/asterix to perform the translation from bits to FL, because you are going to operate with this bits, and only after this operations, yo will encode the bits to FL.

Hope now is more clear.

**Comment by dsalantic** [comment]
I agree with @ifsnop. Asterix parser should return raw ModeC value as it is returned by radar and then user can do with it what he wants (e.g. decode it to flight level using quality bits).
If asterix decoder performs decoding you will lose the original information (and you have flight level there anyway in I090).
Maybe I could just display the ModeC value in bits instead of integer, but I don't think it is very useful since user can do it himself (simple bit manipulation) and it will just increase the payload if you export it to JSON for example.
Thank you both for your contribution and productive discussion.
